"""
Effects System

Implements the effect/skill system for cards. Effects are triggered by
game events and can modify game state, trigger additional effects, etc.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum, auto
from typing import TYPE_CHECKING, Any, Callable, Optional

from app.models.game import (
    Zone,
    EffectTiming,
    GameEvent,
    CardDrawnEvent,
    CardPlayedEvent,
    CardPromotedEvent,
    CardDestroyedEvent,
    DamageDealtEvent,
    AttackDeclaredEvent,
    TurnStartedEvent,
    TurnEndedEvent,
)

if TYPE_CHECKING:
    from app.models.game import GameState, GameCard


class EffectTrigger(Enum):
    """
    Types of triggers that can activate effects.
    """
    # Card lifecycle triggers
    ON_PLAY = auto()           # When this card enters play
    ON_PROMOTE = auto()        # When this card is promoted to attacking zone
    ON_DESTROY = auto()        # When this card is destroyed
    
    # Combat triggers
    ON_ATTACK = auto()         # When this card attacks
    ON_DEFEND = auto()         # When this card is attacked
    ON_DEAL_DAMAGE = auto()    # When this card deals damage
    ON_TAKE_DAMAGE = auto()    # When this card takes damage
    
    # Turn triggers
    ON_TURN_START = auto()     # At the start of owner's turn
    ON_TURN_END = auto()       # At the end of owner's turn
    
    # Other triggers
    ON_DRAW = auto()           # When owner draws a card
    ON_ANY_PLAY = auto()       # When any card is played
    ON_ANY_DESTROY = auto()    # When any card is destroyed
    
    # Passive (always active)
    PASSIVE = auto()           # Always active while in active zone


@dataclass
class EffectContext:
    """
    Context passed to effect handlers.
    
    Attributes:
        state: Current game state
        source_card: Card that owns this effect
        trigger_event: Event that triggered this effect
        trigger: The trigger type
    """
    state: "GameState"
    source_card: "GameCard"
    trigger_event: Optional[GameEvent] = None
    trigger: Optional[EffectTrigger] = None


@dataclass
class EffectResult:
    """
    Result returned by effect handlers.
    
    Attributes:
        events: New events generated by this effect
        state_modifications: Description of state changes
        prevent_default: If True, prevents the default action
    """
    events: list[GameEvent] = field(default_factory=list)
    state_modifications: list[str] = field(default_factory=list)
    prevent_default: bool = False


class Effect(ABC):
    """
    Base class for all effects.
    
    Subclass this to implement specific skills and abilities.
    """
    
    def __init__(self, effect_id: str, name: str, description: str = ""):
        self.effect_id = effect_id
        self.name = name
        self.description = description
    
    @property
    @abstractmethod
    def triggers(self) -> list[EffectTrigger]:
        """Return list of triggers this effect responds to."""
        pass
    
    def should_trigger(self, context: EffectContext) -> bool:
        """
        Check if this effect should trigger given the context.
        
        Override this for conditional effects.
        """
        # Check if card is in an active zone
        if context.source_card.zone not in (Zone.SUPPORTING, Zone.ATTACKING):
            return False
        return True
    
    @abstractmethod
    def execute(self, context: EffectContext) -> EffectResult:
        """
        Execute the effect.
        
        Returns an EffectResult with any generated events and state changes.
        """
        pass


# ============================================================================
# Passive Effects (Stats/Modifiers)
# ============================================================================

class StatModifierEffect(Effect):
    """
    Effect that modifies stats of cards.
    
    Passive effect that applies stat bonuses/penalties.
    """
    
    def __init__(self, effect_id: str, name: str, description: str = "",
                 attack_bonus: int = 0, defense_bonus: int = 0,
                 health_bonus: int = 0, target_self: bool = True,
                 target_allies: bool = False, target_enemies: bool = False):
        super().__init__(effect_id, name, description)
        self.attack_bonus = attack_bonus
        self.defense_bonus = defense_bonus
        self.health_bonus = health_bonus
        self.target_self = target_self
        self.target_allies = target_allies
        self.target_enemies = target_enemies
    
    @property
    def triggers(self) -> list[EffectTrigger]:
        return [EffectTrigger.PASSIVE]
    
    def execute(self, context: EffectContext) -> EffectResult:
        # Passive effects don't generate events directly
        # They modify stats which are calculated dynamically
        return EffectResult(
            state_modifications=[
                f"Apply {self.attack_bonus} attack, {self.defense_bonus} defense, {self.health_bonus} health"
            ]
        )
    
    def get_affected_cards(self, context: EffectContext) -> list["GameCard"]:
        """Get all cards affected by this modifier."""
        affected = []
        owner_id = context.source_card.owner_id
        
        if self.target_self:
            affected.append(context.source_card)
        
        if self.target_allies:
            for card_id in context.state.room.players[owner_id].get_active_cards():
                card = context.state.cards.get(card_id)
                if card and card.instance_id != context.source_card.instance_id:
                    affected.append(card)
        
        if self.target_enemies:
            opponent = context.state.room.get_opponent(owner_id)
            for card_id in opponent.get_active_cards():
                card = context.state.cards.get(card_id)
                if card:
                    affected.append(card)
        
        return affected


class ElementBonusEffect(Effect):
    """
    Effect that provides bonus element contribution.
    """
    
    def __init__(self, effect_id: str, name: str, description: str = "",
                 element_id: int = 0, bonus_amount: int = 1):
        super().__init__(effect_id, name, description)
        self.element_id = element_id
        self.bonus_amount = bonus_amount
    
    @property
    def triggers(self) -> list[EffectTrigger]:
        return [EffectTrigger.PASSIVE]
    
    def execute(self, context: EffectContext) -> EffectResult:
        return EffectResult(
            state_modifications=[
                f"Contribute +{self.bonus_amount} {self.element_id} element"
            ]
        )


# ============================================================================
# Triggered Effects
# ============================================================================

class OnPlayEffect(Effect):
    """
    Effect that triggers when a card enters play.
    """
    
    def __init__(self, effect_id: str, name: str, description: str = "",
                 draw_cards: int = 0, damage_to_enemy: int = 0):
        super().__init__(effect_id, name, description)
        self.draw_cards = draw_cards
        self.damage_to_enemy = damage_to_enemy
    
    @property
    def triggers(self) -> list[EffectTrigger]:
        return [EffectTrigger.ON_PLAY]
    
    def should_trigger(self, context: EffectContext) -> bool:
        if not super().should_trigger(context):
            return False
        # Check if the triggering event is for this card
        if isinstance(context.trigger_event, CardPlayedEvent):
            return context.trigger_event.card_id == context.source_card.instance_id
        return False
    
    def execute(self, context: EffectContext) -> EffectResult:
        events = []
        modifications = []
        
        if self.draw_cards > 0:
            # Drawing is handled by the engine
            modifications.append(f"Draw {self.draw_cards} cards")
        
        if self.damage_to_enemy > 0:
            modifications.append(f"Deal {self.damage_to_enemy} damage to enemy")
        
        return EffectResult(events=events, state_modifications=modifications)


class OnDestroyEffect(Effect):
    """
    Effect that triggers when a card is destroyed.
    """
    
    def __init__(self, effect_id: str, name: str, description: str = "",
                 return_to_hand: bool = False, deal_damage: int = 0,
                 target_attacker: bool = False):
        super().__init__(effect_id, name, description)
        self.return_to_hand = return_to_hand
        self.deal_damage = deal_damage
        self.target_attacker = target_attacker
    
    @property
    def triggers(self) -> list[EffectTrigger]:
        return [EffectTrigger.ON_DESTROY]
    
    def should_trigger(self, context: EffectContext) -> bool:
        if isinstance(context.trigger_event, CardDestroyedEvent):
            return context.trigger_event.card_id == context.source_card.instance_id
        return False
    
    def execute(self, context: EffectContext) -> EffectResult:
        modifications = []
        
        if self.return_to_hand:
            modifications.append("Return to hand instead of graveyard")
        
        if self.deal_damage > 0:
            target = "attacker" if self.target_attacker else "random enemy"
            modifications.append(f"Deal {self.deal_damage} damage to {target}")
        
        return EffectResult(state_modifications=modifications)


class OnAttackEffect(Effect):
    """
    Effect that triggers when this card attacks.
    """
    
    def __init__(self, effect_id: str, name: str, description: str = "",
                 bonus_damage: int = 0, lifesteal: bool = False,
                 attack_twice: bool = False):
        super().__init__(effect_id, name, description)
        self.bonus_damage = bonus_damage
        self.lifesteal = lifesteal
        self.attack_twice = attack_twice
    
    @property
    def triggers(self) -> list[EffectTrigger]:
        return [EffectTrigger.ON_ATTACK]
    
    def should_trigger(self, context: EffectContext) -> bool:
        if isinstance(context.trigger_event, AttackDeclaredEvent):
            return context.trigger_event.attacker_id == context.source_card.instance_id
        return False
    
    def execute(self, context: EffectContext) -> EffectResult:
        modifications = []
        
        if self.bonus_damage > 0:
            modifications.append(f"+{self.bonus_damage} bonus damage")
        
        if self.lifesteal:
            modifications.append("Heal for damage dealt")
        
        if self.attack_twice:
            modifications.append("Attack again")
        
        return EffectResult(state_modifications=modifications)


class OnDefendEffect(Effect):
    """
    Effect that triggers when this card is attacked.
    """
    
    def __init__(self, effect_id: str, name: str, description: str = "",
                 damage_reduction: int = 0, reflect_damage: int = 0,
                 counter_attack: bool = False):
        super().__init__(effect_id, name, description)
        self.damage_reduction = damage_reduction
        self.reflect_damage = reflect_damage
        self.counter_attack = counter_attack
    
    @property
    def triggers(self) -> list[EffectTrigger]:
        return [EffectTrigger.ON_DEFEND]
    
    def should_trigger(self, context: EffectContext) -> bool:
        if isinstance(context.trigger_event, AttackDeclaredEvent):
            return context.trigger_event.target_id == context.source_card.instance_id
        return False
    
    def execute(self, context: EffectContext) -> EffectResult:
        modifications = []
        
        if self.damage_reduction > 0:
            modifications.append(f"Reduce damage by {self.damage_reduction}")
        
        if self.reflect_damage > 0:
            modifications.append(f"Reflect {self.reflect_damage} damage to attacker")
        
        if self.counter_attack:
            modifications.append("Counter attack after being attacked")
        
        return EffectResult(state_modifications=modifications)


class OnTurnStartEffect(Effect):
    """
    Effect that triggers at the start of owner's turn.
    """
    
    def __init__(self, effect_id: str, name: str, description: str = "",
                 heal_amount: int = 0, draw_cards: int = 0,
                 gain_element: int = 0, element_id: int = 0):
        super().__init__(effect_id, name, description)
        self.heal_amount = heal_amount
        self.draw_cards = draw_cards
        self.gain_element = gain_element
        self.element_id = element_id
    
    @property
    def triggers(self) -> list[EffectTrigger]:
        return [EffectTrigger.ON_TURN_START]
    
    def should_trigger(self, context: EffectContext) -> bool:
        if not super().should_trigger(context):
            return False
        if isinstance(context.trigger_event, TurnStartedEvent):
            return context.trigger_event.player_id == context.source_card.owner_id
        return False
    
    def execute(self, context: EffectContext) -> EffectResult:
        modifications = []
        
        if self.heal_amount > 0:
            modifications.append(f"Heal {self.heal_amount} HP")
        
        if self.draw_cards > 0:
            modifications.append(f"Draw {self.draw_cards} cards")
        
        if self.gain_element > 0:
            modifications.append(f"Gain {self.gain_element} element {self.element_id}")
        
        return EffectResult(state_modifications=modifications)


# ============================================================================
# Effect Registry
# ============================================================================

class EffectRegistry:
    """
    Registry for all available effects.
    
    Effects are registered by ID and can be looked up to create instances.
    """
    
    _effects: dict[str, type[Effect]] = {}
    _instances: dict[str, Effect] = {}
    
    @classmethod
    def register(cls, effect_class: type[Effect], effect_id: str) -> None:
        """Register an effect class."""
        cls._effects[effect_id] = effect_class
    
    @classmethod
    def get_effect_class(cls, effect_id: str) -> Optional[type[Effect]]:
        """Get an effect class by ID."""
        return cls._effects.get(effect_id)
    
    @classmethod
    def create_effect(cls, effect_id: str, **kwargs) -> Optional[Effect]:
        """Create an effect instance by ID."""
        effect_class = cls._effects.get(effect_id)
        if effect_class:
            return effect_class(effect_id=effect_id, **kwargs)
        return None
    
    @classmethod
    def register_instance(cls, effect: Effect) -> None:
        """Register a pre-configured effect instance."""
        cls._instances[effect.effect_id] = effect
    
    @classmethod
    def get_effect(cls, effect_id: str) -> Optional[Effect]:
        """Get a registered effect instance."""
        return cls._instances.get(effect_id)


# Register built-in effects
EffectRegistry.register(StatModifierEffect, "stat_modifier")
EffectRegistry.register(ElementBonusEffect, "element_bonus")
EffectRegistry.register(OnPlayEffect, "on_play")
EffectRegistry.register(OnDestroyEffect, "on_destroy")
EffectRegistry.register(OnAttackEffect, "on_attack")
EffectRegistry.register(OnDefendEffect, "on_defend")
EffectRegistry.register(OnTurnStartEffect, "on_turn_start")

