"""
Event Loop

Processes events through the game pipeline:
1. Apply event to state via reducer
2. Trigger effects that react to the event
3. Queue any new events generated by effects
4. Repeat until queue is empty
5. Auto-advance through phases with no available actions

This creates a complete event-driven processing system.
"""

from __future__ import annotations

from collections import deque
from dataclasses import dataclass, field
from typing import TYPE_CHECKING

from app.game.effects import EffectContext, EffectTrigger
from app.game.reducer import apply_event
from app.models.game.enums import GameStatus, StatusType, Zone
from app.models.game.events import (
    AttackDeclaredEvent,
    AttackResolvedEvent,
    CardAssociatedEvent,
    CardDestroyedEvent,
    CardHealthChangedEvent,
    CardPlayedEvent,
    CardPromotedEvent,
    DamageDealtEvent,
    GameEvent,
    StatusExpiredEvent,
    StatusTickedEvent,
    TurnEndedEvent,
    TurnStartedEvent,
)

if TYPE_CHECKING:
    from app.models.game.card import ActiveStatus, GameCard
    from app.models.game.player import PlayerState
    from app.models.game.state import GameState


@dataclass
class EventLoopResult:
    """
    Result of processing events through the loop.

    Attributes:
        final_state: The state after all events applied
        final_players: The players dict after all events applied
        all_events: All events that were processed (including triggered ones)
        triggered_events: Events generated by effects
    """

    final_state: GameState
    final_players: dict[str, PlayerState]
    all_events: list[GameEvent] = field(default_factory=list)
    triggered_events: list[GameEvent] = field(default_factory=list)


# Mapping from event types to effect triggers (for generic all-cards triggers).
# AttackDeclaredEvent and DamageDealtEvent are handled specially in
# _get_trigger_pairs because they target specific cards with different triggers.
EVENT_TO_TRIGGER: dict[type[GameEvent], EffectTrigger] = {
    CardPlayedEvent: EffectTrigger.ON_PLAY,
    CardPromotedEvent: EffectTrigger.ON_PROMOTE,
    CardDestroyedEvent: EffectTrigger.ON_DESTROY,
    CardAssociatedEvent: EffectTrigger.ON_ASSOCIATE,
    TurnStartedEvent: EffectTrigger.ON_TURN_START,
    TurnEndedEvent: EffectTrigger.ON_TURN_END,
    AttackResolvedEvent: EffectTrigger.ON_ATTACK_RESOLVE,
}


class EventLoop:
    """
    Processes events through the complete pipeline.

    The event loop:
    1. Takes initial events from action evaluation
    2. Applies each event through the reducer
    3. Checks for triggered effects
    4. Queues any new events from effects
    5. Repeats until queue is empty
    """

    def __init__(self, max_iterations: int = 1000):
        """
        Initialize the event loop.

        Args:
            max_iterations: Safety limit to prevent infinite loops
        """
        self.max_iterations = max_iterations

    def process(
        self,
        state: GameState,
        players: dict[str, PlayerState],
        initial_events: list[GameEvent],
    ) -> EventLoopResult:
        """
        Process events through the complete loop.

        Args:
            state: Initial game state
            players: Initial players dict
            initial_events: Events from action evaluation

        Returns:
            EventLoopResult with final state, players, and all events
        """

        # No need to copy - apply_event returns new objects each time
        current_state = state
        current_players = players
        event_queue: deque[GameEvent] = deque(initial_events)
        all_events: list[GameEvent] = []
        triggered_events: list[GameEvent] = []
        iterations = 0
        auto_advance_passes = 0
        max_auto_advance = 14  # safety cap: 7 phases × 2 players

        while iterations < self.max_iterations:
            # Process all events in queue
            while event_queue and iterations < self.max_iterations:
                iterations += 1
                event = event_queue.popleft()

                # 1. Apply event to state and players through reducer
                current_state, current_players = apply_event(current_state, current_players, event)
                all_events.append(event)

                # 2. Queue status ticks/expirations, then triggered effects
                new_events = self._process_statuses(current_state, event)
                new_events.extend(self._process_effects(current_state, current_players, event))

                # 3. Queue any new events
                for new_event in new_events:
                    event_queue.append(new_event)
                    triggered_events.append(new_event)

            # 4. Queue drained — auto-advance if current phase has no actions
            if auto_advance_passes >= max_auto_advance:
                break

            advance_events = self._get_auto_advance_events(current_state)
            if not advance_events:
                break

            auto_advance_passes += 1
            for e in advance_events:
                event_queue.append(e)

        return EventLoopResult(
            final_state=current_state,
            final_players=current_players,
            all_events=all_events,
            triggered_events=triggered_events,
        )

    def _get_auto_advance_events(self, state: GameState) -> list[GameEvent]:
        """If the current phase has no phase-specific actions, generate pass events to advance."""
        from app.game.actions import ACTION_TYPES, PassPhaseAction

        if state.status != GameStatus.IN_PROGRESS:
            return []
        if state.active_player_id is None:
            return []

        for action_cls in ACTION_TYPES.values():
            phases = action_cls.model_fields["valid_phases"].default
            if phases and state.current_phase in phases and action_cls.get_valid(state, state.active_player_id):
                return []

        pass_action = PassPhaseAction(player_id=state.active_player_id)
        return pass_action.to_events(state)

    def _process_effects(self, state: GameState, players: dict[str, PlayerState], event: GameEvent) -> list[GameEvent]:
        """
        Process effects that react to an event.

        Uses _get_trigger_pairs to determine exactly which (trigger, card)
        combinations to evaluate for each event type. This avoids double-firing
        and correctly routes multi-trigger events (e.g. AttackDeclaredEvent
        fires ON_ATTACK on the attacker and ON_DEFEND on the target).

        Args:
            state: Current game state (after event applied)
            players: Current players dict
            event: The event that just occurred

        Returns:
            List of new events generated by effects
        """
        new_events: list[GameEvent] = []

        trigger_pairs = self._get_trigger_pairs(state, players, event)
        if not trigger_pairs:
            return new_events

        for trigger, card_id in trigger_pairs:
            card = state.cards.get(card_id)
            if not card:
                continue

            for effect in card.effect_atoms:
                if trigger not in effect.triggers:
                    continue

                context = EffectContext(
                    state=state,
                    source_card=card,
                    trigger_event=event,
                    trigger=trigger,
                )

                if effect.should_trigger(context):
                    result = effect.execute(context)
                    new_events.extend(result.events)

        return new_events

    def _get_trigger_pairs(
        self,
        state: GameState,
        players: dict[str, PlayerState],
        event: GameEvent,
    ) -> list[tuple[EffectTrigger, str]]:
        """
        Return (trigger, card_id) pairs to evaluate for an event.

        Combat events map to specific cards with specific triggers:
        - AttackDeclaredEvent → ON_ATTACK for attacker, ON_DEFEND for target
        - DamageDealtEvent   → ON_DEAL_DAMAGE for source, ON_TAKE_DAMAGE for target

        All other mapped events fire their trigger on every active card.
        """
        pairs: list[tuple[EffectTrigger, str]] = []

        if isinstance(event, AttackDeclaredEvent):
            pairs.append((EffectTrigger.ON_ATTACK, event.attacker_id))
            attacker = state.cards.get(event.attacker_id)
            if attacker:
                for assoc_id in attacker.associations:
                    pairs.append((EffectTrigger.ON_ATTACK, assoc_id))
            if event.target_id:
                pairs.append((EffectTrigger.ON_DEFEND, event.target_id))
            if attacker:
                for card_id in players[attacker.owner_id].get_active_cards():
                    if card_id != event.attacker_id:
                        pairs.append((EffectTrigger.ON_ALLY_ATTACK, card_id))
        elif isinstance(event, DamageDealtEvent):
            pairs.append((EffectTrigger.ON_DEAL_DAMAGE, event.source_id))
            pairs.append((EffectTrigger.ON_TAKE_DAMAGE, event.target_id))
        elif isinstance(event, CardAssociatedEvent):
            pairs.append((EffectTrigger.ON_ASSOCIATE, event.association_card_id))
            pairs.append((EffectTrigger.ON_ASSOCIATE_TARGET, event.association_card_id))
            pairs.append((EffectTrigger.ON_ASSOCIATE_TARGET, event.target_card_id))
        elif isinstance(event, AttackResolvedEvent):
            pairs.append((EffectTrigger.ON_ATTACK_RESOLVE, event.attacker_id))
        else:
            # Generic: trigger on all active cards
            trigger = EVENT_TO_TRIGGER.get(type(event))
            if not trigger:
                return pairs
            for player in players.values():
                for card_id in player.get_active_cards():
                    pairs.append((trigger, card_id))

        return pairs

    def _process_statuses(self, state: GameState, event: GameEvent) -> list[GameEvent]:
        """At each turn start/end, synthesize status tick/expiry (and DoT) events.

        The reducer performs the actual mutation; this only emits events whose
        `tick_on`/`expires_on` timing matches the current turn boundary.
        """
        if not isinstance(event, (TurnStartedEvent, TurnEndedEvent)):
            return []

        suffix = "start" if isinstance(event, TurnStartedEvent) else "end"
        queued: list[GameEvent] = []
        for card in list(state.cards.values()):
            if card.zone in (Zone.DECK, Zone.EXILED):
                continue
            relation = "own" if card.owner_id == event.player_id else "opp"
            timing = f"{relation}_turn_{suffix}"
            for status in list(card.active_statuses):
                if status.tick_on == timing:
                    queued.extend(_tick_status_events(state, card, status))
                elif status.expires_on == timing:
                    queued.append(
                        StatusExpiredEvent(
                            game_id=state.game_id, target_id=card.instance_id, status_id=status.status_id
                        )
                    )
        return queued


def _tick_status_events(state: GameState, card: GameCard, status: ActiveStatus) -> list[GameEvent]:
    """Events for one status whose tick timing fired this turn boundary.

    A delayed DoT only consumes one delay tick (duration does not count down
    yet). Otherwise a DoT deals its damage, then — like any ticking status —
    the duration counts down and expires when exhausted.
    """
    if status.status_type == StatusType.DAMAGE_OVER_TIME and int(status.payload.get("delay_turns", 0)) > 0:
        return [StatusTickedEvent(game_id=state.game_id, target_id=card.instance_id, status_id=status.status_id)]

    events: list[GameEvent] = []
    if status.status_type == StatusType.DAMAGE_OVER_TIME:
        events.extend(_dot_damage_events(state, card, status))
    if status.remaining_turns > 0:
        events.append(StatusTickedEvent(game_id=state.game_id, target_id=card.instance_id, status_id=status.status_id))
        if status.remaining_turns <= 1:
            events.append(
                StatusExpiredEvent(game_id=state.game_id, target_id=card.instance_id, status_id=status.status_id)
            )
    return events


def _dot_damage_events(state: GameState, card: GameCard, status: ActiveStatus) -> list[GameEvent]:
    """A damage-over-time health change plus destruction when it drops to 0."""
    amount = int(status.payload.get("amount", 0))
    new_health = card.current_health - amount
    events: list[GameEvent] = [
        CardHealthChangedEvent(
            game_id=state.game_id,
            target_id=card.instance_id,
            source_id=status.source_card_id,
            delta=-amount,
            new_health=new_health,
            reason="damage_over_time",
        )
    ]
    if new_health <= 0:
        source = state.cards.get(status.source_card_id)
        events.append(
            CardDestroyedEvent(
                game_id=state.game_id,
                instance_id=card.instance_id,
                owner_id=card.owner_id,
                card_name=card.name,
                destroyed_by=source.instance_id if source else None,
            )
        )
    return events
