"""
Event Loop

Processes events through the game pipeline:
1. Apply event to state via reducer
2. Trigger effects/skills that react to the event
3. Queue any new events generated by effects
4. Repeat until queue is empty

This creates a complete event-driven processing system.
"""

from __future__ import annotations

from collections import deque
from dataclasses import dataclass, field
from typing import TYPE_CHECKING

from app.models.game.events import (
    GameEvent,
    CardPlayedEvent,
    CardPromotedEvent,
    CardDestroyedEvent,
    AttackDeclaredEvent,
    DamageDealtEvent,
    TurnStartedEvent,
    TurnEndedEvent,
)
from app.game.effects import EffectTrigger, EffectContext, get_effect
from app.game.reducer import apply_event

if TYPE_CHECKING:
    from app.models.game.state import GameState
    from app.models.game.player import PlayerState


@dataclass
class EventLoopResult:
    """
    Result of processing events through the loop.
    
    Attributes:
        final_state: The state after all events applied
        final_players: The players dict after all events applied
        all_events: All events that were processed (including triggered ones)
        triggered_events: Events generated by effects
    """
    final_state: "GameState"
    final_players: dict[str, "PlayerState"]
    all_events: list[GameEvent] = field(default_factory=list)
    triggered_events: list[GameEvent] = field(default_factory=list)


# Mapping from event types to effect triggers (for generic all-cards triggers).
# AttackDeclaredEvent and DamageDealtEvent are handled specially in
# _get_trigger_pairs because they target specific cards with different triggers.
EVENT_TO_TRIGGER: dict[type[GameEvent], EffectTrigger] = {
    CardPlayedEvent: EffectTrigger.ON_PLAY,
    CardPromotedEvent: EffectTrigger.ON_PROMOTE,
    CardDestroyedEvent: EffectTrigger.ON_DESTROY,
    TurnStartedEvent: EffectTrigger.ON_TURN_START,
    TurnEndedEvent: EffectTrigger.ON_TURN_END,
}


class EventLoop:
    """
    Processes events through the complete pipeline.
    
    The event loop:
    1. Takes initial events from action evaluation
    2. Applies each event through the reducer
    3. Checks for triggered effects
    4. Queues any new events from effects
    5. Repeats until queue is empty
    """
    
    def __init__(self, max_iterations: int = 1000):
        """
        Initialize the event loop.
        
        Args:
            max_iterations: Safety limit to prevent infinite loops
        """
        self.max_iterations = max_iterations
    
    def process(self, state: "GameState", players: dict[str, "PlayerState"], initial_events: list[GameEvent]) -> EventLoopResult:
        """
        Process events through the complete loop.
        
        Args:
            state: Initial game state
            players: Initial players dict
            initial_events: Events from action evaluation
        
        Returns:
            EventLoopResult with final state, players, and all events
        """
        from app.models.game.player import PlayerState
        
        # No need to copy - apply_event returns new objects each time
        current_state = state
        current_players = players
        event_queue: deque[GameEvent] = deque(initial_events)
        all_events: list[GameEvent] = []
        triggered_events: list[GameEvent] = []
        iterations = 0
        
        while event_queue and iterations < self.max_iterations:
            iterations += 1
            event = event_queue.popleft()
            
            # 1. Apply event to state and players through reducer
            current_state, current_players = apply_event(current_state, current_players, event)
            
            # 2. Log the event
            current_state.log_event(event.model_dump(mode='json'))
            all_events.append(event)
            
            # 3. Check for triggered effects
            new_events = self._process_effects(current_state, current_players, event)
            
            # 4. Queue any new events
            for new_event in new_events:
                event_queue.append(new_event)
                triggered_events.append(new_event)
        
        return EventLoopResult(
            final_state=current_state,
            final_players=current_players,
            all_events=all_events,
            triggered_events=triggered_events,
        )
    
    def _process_effects(self, state: "GameState", players: dict[str, "PlayerState"], event: GameEvent) -> list[GameEvent]:
        """
        Process effects that react to an event.

        Uses _get_trigger_pairs to determine exactly which (trigger, card)
        combinations to evaluate for each event type. This avoids double-firing
        and correctly routes multi-trigger events (e.g. AttackDeclaredEvent
        fires ON_ATTACK on the attacker and ON_DEFEND on the target).

        Args:
            state: Current game state (after event applied)
            players: Current players dict
            event: The event that just occurred

        Returns:
            List of new events generated by effects
        """
        new_events: list[GameEvent] = []

        trigger_pairs = self._get_trigger_pairs(state, players, event)
        if not trigger_pairs:
            return new_events

        for trigger, card_id in trigger_pairs:
            card = state.cards.get(card_id)
            if not card:
                continue

            for skill_id in card.skill_ids:
                effect = get_effect(str(skill_id))
                if not effect:
                    continue

                if trigger not in effect.triggers:
                    continue

                context = EffectContext(
                    state=state,
                    source_card=card,
                    trigger_event=event,
                    trigger=trigger,
                )

                if effect.should_trigger(context):
                    result = effect.execute(context)
                    new_events.extend(result.events)

        return new_events

    def _get_trigger_pairs(
        self,
        state: "GameState",
        players: dict[str, "PlayerState"],
        event: GameEvent,
    ) -> list[tuple[EffectTrigger, str]]:
        """
        Return (trigger, card_id) pairs to evaluate for an event.

        Combat events map to specific cards with specific triggers:
        - AttackDeclaredEvent → ON_ATTACK for attacker, ON_DEFEND for target
        - DamageDealtEvent   → ON_DEAL_DAMAGE for source, ON_TAKE_DAMAGE for target

        All other mapped events fire their trigger on every active card.
        """
        pairs: list[tuple[EffectTrigger, str]] = []

        if isinstance(event, AttackDeclaredEvent):
            pairs.append((EffectTrigger.ON_ATTACK, event.attacker_id))
            if event.target_id:
                pairs.append((EffectTrigger.ON_DEFEND, event.target_id))
        elif isinstance(event, DamageDealtEvent):
            pairs.append((EffectTrigger.ON_DEAL_DAMAGE, event.source_id))
            pairs.append((EffectTrigger.ON_TAKE_DAMAGE, event.target_id))
        else:
            # Generic: trigger on all active cards
            trigger = EVENT_TO_TRIGGER.get(type(event))
            if not trigger:
                return pairs
            for player in players.values():
                for card_id in player.get_active_cards():
                    pairs.append((trigger, card_id))

        return pairs
