"""add user_cards table

Revision ID: 4588442c7050
Revises: allow_repeated_cards
Create Date: 2026-05-20 14:39:30.697945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4588442c7050'
down_revision: Union[str, Sequence[str], None] = 'allow_repeated_cards'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create enum type before converting existing columns to use it
    actiontype = sa.Enum('physical', 'magical', name='actiontype')
    actiontype.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_cards',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'card_id')
    )
    op.alter_column('abilities', 'type',
               existing_type=sa.VARCHAR(length=50),
               type_=actiontype,
               existing_nullable=True,
               postgresql_using="type::actiontype")
    op.alter_column('attacks', 'type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('physical', 'magical', name='actiontype'),
               existing_nullable=True,
               postgresql_using="type::actiontype")

    op.execute("UPDATE cards SET forces = '[]'::jsonb WHERE forces IS NULL")
    op.alter_column('cards', 'forces',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'forces',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('attacks', 'type',
               existing_type=sa.Enum('physical', 'magical', name='actiontype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('abilities', 'type',
               existing_type=sa.Enum('physical', 'magical', name='actiontype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    actiontype = sa.Enum('physical', 'magical', name='actiontype')
    actiontype.drop(op.get_bind(), checkfirst=True)

    op.drop_table('user_cards')
    # ### end Alembic commands ###
