
/**
 * Generated by Babylon.js Editor
 */

import { loadScene, scriptsDictionary, scriptAssetsCache, _applyScriptsForObject, _removeRegisteredScriptInstance, _preloadScriptsAssets } from "babylonjs-editor-tools";
import * as scripts_GameNetworkManagerComponent from "./scripts/GameNetworkManagerComponent";
import * as scripts_HoverAnimation from "./scripts/HoverAnimation";
import * as scripts_box from "./scripts/box";
import * as scripts_BoardController from "./scripts/BoardController";
import * as scripts_InteractionManager from "./scripts/interaction/InteractionManager";
import * as scripts_HudController from "./scripts/hud/HudController";

export const scriptsMap = {
    "scripts/GameNetworkManagerComponent.ts": scripts_GameNetworkManagerComponent,
	"scripts/HoverAnimation.ts": scripts_HoverAnimation,
	"scripts/box.ts": scripts_box,
	"scripts/BoardController.ts": scripts_BoardController,
	"scripts/interaction/InteractionManager.ts": scripts_InteractionManager,
	"scripts/hud/HudController.ts": scripts_HudController
};

export { loadScene, scriptsDictionary, scriptAssetsCache, _applyScriptsForObject, _removeRegisteredScriptInstance, _preloadScriptsAssets };
