// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  type Options as Options2,
  type TDataShape,
  urlSearchParamsBodySerializer,
} from "./client";
import { client } from "./client.gen";
import type {
  AddCardToDeckDecksDeckIdCardsCardIdPostData,
  AddCardToDeckDecksDeckIdCardsCardIdPostErrors,
  AddCardToDeckDecksDeckIdCardsCardIdPostResponses,
  CreateAbilityAbilitiesPostData,
  CreateAbilityAbilitiesPostErrors,
  CreateAbilityAbilitiesPostResponses,
  CreateAssociationAssociationsPostData,
  CreateAssociationAssociationsPostErrors,
  CreateAssociationAssociationsPostResponses,
  CreateAttackAttacksPostData,
  CreateAttackAttacksPostErrors,
  CreateAttackAttacksPostResponses,
  CreateCardCardsPostData,
  CreateCardCardsPostErrors,
  CreateCardCardsPostResponses,
  CreateCharacterCharactersPostData,
  CreateCharacterCharactersPostErrors,
  CreateCharacterCharactersPostResponses,
  CreateDeckDecksPostData,
  CreateDeckDecksPostErrors,
  CreateDeckDecksPostResponses,
  CreateElementElementsPostData,
  CreateElementElementsPostErrors,
  CreateElementElementsPostResponses,
  CreateTypeTypesPostData,
  CreateTypeTypesPostErrors,
  CreateTypeTypesPostResponses,
  DeleteAbilityAbilitiesAbilityIdDeleteData,
  DeleteAbilityAbilitiesAbilityIdDeleteErrors,
  DeleteAbilityAbilitiesAbilityIdDeleteResponses,
  DeleteAssociationAssociationsAssociationIdDeleteData,
  DeleteAssociationAssociationsAssociationIdDeleteErrors,
  DeleteAssociationAssociationsAssociationIdDeleteResponses,
  DeleteAttackAttacksAttackIdDeleteData,
  DeleteAttackAttacksAttackIdDeleteErrors,
  DeleteAttackAttacksAttackIdDeleteResponses,
  DeleteCardCardsCardIdDeleteData,
  DeleteCardCardsCardIdDeleteErrors,
  DeleteCardCardsCardIdDeleteResponses,
  DeleteCharacterCharactersCharacterIdDeleteData,
  DeleteCharacterCharactersCharacterIdDeleteErrors,
  DeleteCharacterCharactersCharacterIdDeleteResponses,
  DeleteDeckDecksDeckIdDeleteData,
  DeleteDeckDecksDeckIdDeleteErrors,
  DeleteDeckDecksDeckIdDeleteResponses,
  DeleteElementElementsElementIdDeleteData,
  DeleteElementElementsElementIdDeleteErrors,
  DeleteElementElementsElementIdDeleteResponses,
  DeleteTypeTypesTypeIdDeleteData,
  DeleteTypeTypesTypeIdDeleteErrors,
  DeleteTypeTypesTypeIdDeleteResponses,
  GetAbilityAbilitiesValueGetData,
  GetAbilityAbilitiesValueGetErrors,
  GetAbilityAbilitiesValueGetResponses,
  GetAllAbilitiesAbilitiesGetData,
  GetAllAbilitiesAbilitiesGetResponses,
  GetAllAssociationsAssociationsGetData,
  GetAllAssociationsAssociationsGetResponses,
  GetAllAttacksAttacksGetData,
  GetAllAttacksAttacksGetResponses,
  GetAllCardsCardsGetData,
  GetAllCardsCardsGetResponses,
  GetAllCharactersCharactersGetData,
  GetAllCharactersCharactersGetResponses,
  GetAllDecksDecksGetData,
  GetAllDecksDecksGetResponses,
  GetAllElementsElementsGetData,
  GetAllElementsElementsGetResponses,
  GetAllTypesTypesGetData,
  GetAllTypesTypesGetResponses,
  GetAssociationAssociationsValueGetData,
  GetAssociationAssociationsValueGetErrors,
  GetAssociationAssociationsValueGetResponses,
  GetAttackAttacksValueGetData,
  GetAttackAttacksValueGetErrors,
  GetAttackAttacksValueGetResponses,
  GetCardCardsValueGetData,
  GetCardCardsValueGetErrors,
  GetCardCardsValueGetResponses,
  GetCardsByAbilityCardsByAbilityAbilityCodeGetData,
  GetCardsByAbilityCardsByAbilityAbilityCodeGetErrors,
  GetCardsByAbilityCardsByAbilityAbilityCodeGetResponses,
  GetCardsByAssociationCardsByAssociationAssociationCodeGetData,
  GetCardsByAssociationCardsByAssociationAssociationCodeGetErrors,
  GetCardsByAssociationCardsByAssociationAssociationCodeGetResponses,
  GetCardsByAttackCardsByAttackAttackCodeGetData,
  GetCardsByAttackCardsByAttackAttackCodeGetErrors,
  GetCardsByAttackCardsByAttackAttackCodeGetResponses,
  GetCharacterCharactersValueGetData,
  GetCharacterCharactersValueGetErrors,
  GetCharacterCharactersValueGetResponses,
  GetDeckDecksDeckIdGetData,
  GetDeckDecksDeckIdGetErrors,
  GetDeckDecksDeckIdGetResponses,
  GetDeckSummariesDecksSummariesGetData,
  GetDeckSummariesDecksSummariesGetResponses,
  GetElementElementsValueGetData,
  GetElementElementsValueGetErrors,
  GetElementElementsValueGetResponses,
  GetTypeTypesValueGetData,
  GetTypeTypesValueGetErrors,
  GetTypeTypesValueGetResponses,
  ListGameRoomsGameRoomsGetData,
  ListGameRoomsGameRoomsGetResponses,
  LoginForAccessTokenAuthTokenPostData,
  LoginForAccessTokenAuthTokenPostErrors,
  LoginForAccessTokenAuthTokenPostResponses,
  ReadUsersMeAuthMeGetData,
  ReadUsersMeAuthMeGetResponses,
  RegisterUserAuthRegisterPostData,
  RegisterUserAuthRegisterPostErrors,
  RegisterUserAuthRegisterPostResponses,
  RemoveCardFromDeckDecksDeckIdCardsCardIdDeleteData,
  RemoveCardFromDeckDecksDeckIdCardsCardIdDeleteErrors,
  RemoveCardFromDeckDecksDeckIdCardsCardIdDeleteResponses,
  RootGetData,
  RootGetResponses,
  UpdateDeckDecksDeckIdPutData,
  UpdateDeckDecksDeckIdPutErrors,
  UpdateDeckDecksDeckIdPutResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Login For Access Token
 *
 * OAuth2 compatible token login, get an access token for future requests.
 */
export const loginForAccessTokenAuthTokenPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<LoginForAccessTokenAuthTokenPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    LoginForAccessTokenAuthTokenPostResponses,
    LoginForAccessTokenAuthTokenPostErrors,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    url: "/auth/token",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Register User
 *
 * Register a new user.
 */
export const registerUserAuthRegisterPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<RegisterUserAuthRegisterPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    RegisterUserAuthRegisterPostResponses,
    RegisterUserAuthRegisterPostErrors,
    ThrowOnError
  >({
    url: "/auth/register",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Read Users Me
 *
 * Get current authenticated user.
 */
export const readUsersMeAuthMeGet = <ThrowOnError extends boolean = false>(
  options?: Options<ReadUsersMeAuthMeGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ReadUsersMeAuthMeGetResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/auth/me",
    ...options,
  });

/**
 * Get All Elements
 *
 * Get all elements.
 */
export const getAllElementsElementsGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetAllElementsElementsGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetAllElementsElementsGetResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/elements",
    ...options,
  });

/**
 * Create Element
 *
 * Create a new element.
 */
export const createElementElementsPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateElementElementsPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateElementElementsPostResponses,
    CreateElementElementsPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/elements",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Element
 *
 * Get element by ID or label.
 */
export const getElementElementsValueGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetElementElementsValueGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetElementElementsValueGetResponses,
    GetElementElementsValueGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/elements/{value}",
    ...options,
  });

/**
 * Delete Element
 *
 * Delete an element by ID.
 */
export const deleteElementElementsElementIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteElementElementsElementIdDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteElementElementsElementIdDeleteResponses,
    DeleteElementElementsElementIdDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/elements/{element_id}",
    ...options,
  });

/**
 * Get All Types
 *
 * Get all types.
 */
export const getAllTypesTypesGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetAllTypesTypesGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetAllTypesTypesGetResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/types",
    ...options,
  });

/**
 * Create Type
 *
 * Create a new type.
 */
export const createTypeTypesPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateTypeTypesPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateTypeTypesPostResponses,
    CreateTypeTypesPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/types",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Type
 *
 * Get type by ID or label.
 */
export const getTypeTypesValueGet = <ThrowOnError extends boolean = false>(
  options: Options<GetTypeTypesValueGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetTypeTypesValueGetResponses,
    GetTypeTypesValueGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/types/{value}",
    ...options,
  });

/**
 * Delete Type
 *
 * Delete a type by ID.
 */
export const deleteTypeTypesTypeIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteTypeTypesTypeIdDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteTypeTypesTypeIdDeleteResponses,
    DeleteTypeTypesTypeIdDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/types/{type_id}",
    ...options,
  });

/**
 * Get All Characters
 *
 * Get all characters.
 */
export const getAllCharactersCharactersGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetAllCharactersCharactersGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetAllCharactersCharactersGetResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/characters",
    ...options,
  });

/**
 * Create Character
 *
 * Create a new character.
 */
export const createCharacterCharactersPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateCharacterCharactersPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateCharacterCharactersPostResponses,
    CreateCharacterCharactersPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/characters",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Character
 *
 * Get character by ID or label.
 */
export const getCharacterCharactersValueGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetCharacterCharactersValueGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetCharacterCharactersValueGetResponses,
    GetCharacterCharactersValueGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/characters/{value}",
    ...options,
  });

/**
 * Delete Character
 *
 * Delete a character by ID.
 */
export const deleteCharacterCharactersCharacterIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteCharacterCharactersCharacterIdDeleteData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).delete<
    DeleteCharacterCharactersCharacterIdDeleteResponses,
    DeleteCharacterCharactersCharacterIdDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/characters/{character_id}",
    ...options,
  });

/**
 * Get All Attacks
 *
 * Get all attacks with enriched data.
 */
export const getAllAttacksAttacksGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetAllAttacksAttacksGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetAllAttacksAttacksGetResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/attacks",
    ...options,
  });

/**
 * Create Attack
 *
 * Create a new attack.
 */
export const createAttackAttacksPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateAttackAttacksPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateAttackAttacksPostResponses,
    CreateAttackAttacksPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/attacks",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Attack
 *
 * Get attack by code or name.
 */
export const getAttackAttacksValueGet = <ThrowOnError extends boolean = false>(
  options: Options<GetAttackAttacksValueGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetAttackAttacksValueGetResponses,
    GetAttackAttacksValueGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/attacks/{value}",
    ...options,
  });

/**
 * Delete Attack
 *
 * Delete an attack by ID.
 */
export const deleteAttackAttacksAttackIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteAttackAttacksAttackIdDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteAttackAttacksAttackIdDeleteResponses,
    DeleteAttackAttacksAttackIdDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/attacks/{attack_id}",
    ...options,
  });

/**
 * Get All Abilities
 *
 * Get all abilities.
 */
export const getAllAbilitiesAbilitiesGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetAllAbilitiesAbilitiesGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetAllAbilitiesAbilitiesGetResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/abilities",
    ...options,
  });

/**
 * Create Ability
 *
 * Create a new ability.
 */
export const createAbilityAbilitiesPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateAbilityAbilitiesPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateAbilityAbilitiesPostResponses,
    CreateAbilityAbilitiesPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/abilities",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Ability
 *
 * Get ability by code or name.
 */
export const getAbilityAbilitiesValueGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetAbilityAbilitiesValueGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetAbilityAbilitiesValueGetResponses,
    GetAbilityAbilitiesValueGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/abilities/{value}",
    ...options,
  });

/**
 * Delete Ability
 *
 * Delete an ability by ID.
 */
export const deleteAbilityAbilitiesAbilityIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteAbilityAbilitiesAbilityIdDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteAbilityAbilitiesAbilityIdDeleteResponses,
    DeleteAbilityAbilitiesAbilityIdDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/abilities/{ability_id}",
    ...options,
  });

/**
 * Get All Associations
 *
 * Get all associations.
 */
export const getAllAssociationsAssociationsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetAllAssociationsAssociationsGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetAllAssociationsAssociationsGetResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/associations",
    ...options,
  });

/**
 * Create Association
 *
 * Create a new association.
 */
export const createAssociationAssociationsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateAssociationAssociationsPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateAssociationAssociationsPostResponses,
    CreateAssociationAssociationsPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/associations",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Association
 *
 * Get association by code or name.
 */
export const getAssociationAssociationsValueGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetAssociationAssociationsValueGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetAssociationAssociationsValueGetResponses,
    GetAssociationAssociationsValueGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/associations/{value}",
    ...options,
  });

/**
 * Delete Association
 *
 * Delete an association by ID.
 */
export const deleteAssociationAssociationsAssociationIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteAssociationAssociationsAssociationIdDeleteData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).delete<
    DeleteAssociationAssociationsAssociationIdDeleteResponses,
    DeleteAssociationAssociationsAssociationIdDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/associations/{association_id}",
    ...options,
  });

/**
 * Get All Cards
 *
 * Get all cards with enriched data.
 */
export const getAllCardsCardsGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetAllCardsCardsGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetAllCardsCardsGetResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/cards",
    ...options,
  });

/**
 * Create Card
 *
 * Create a new card.
 */
export const createCardCardsPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateCardCardsPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateCardCardsPostResponses,
    CreateCardCardsPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/cards",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Card
 *
 * Get card by code, handle, or name.
 */
export const getCardCardsValueGet = <ThrowOnError extends boolean = false>(
  options: Options<GetCardCardsValueGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetCardCardsValueGetResponses,
    GetCardCardsValueGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/cards/{value}",
    ...options,
  });

/**
 * Get Cards By Attack
 *
 * Get all cards that have a specific attack.
 */
export const getCardsByAttackCardsByAttackAttackCodeGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetCardsByAttackCardsByAttackAttackCodeGetData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).get<
    GetCardsByAttackCardsByAttackAttackCodeGetResponses,
    GetCardsByAttackCardsByAttackAttackCodeGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/cards/by-attack/{attack_code}",
    ...options,
  });

/**
 * Get Cards By Ability
 *
 * Get all cards that have a specific ability.
 */
export const getCardsByAbilityCardsByAbilityAbilityCodeGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetCardsByAbilityCardsByAbilityAbilityCodeGetData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).get<
    GetCardsByAbilityCardsByAbilityAbilityCodeGetResponses,
    GetCardsByAbilityCardsByAbilityAbilityCodeGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/cards/by-ability/{ability_code}",
    ...options,
  });

/**
 * Get Cards By Association
 *
 * Get all cards that have a specific association.
 */
export const getCardsByAssociationCardsByAssociationAssociationCodeGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetCardsByAssociationCardsByAssociationAssociationCodeGetData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).get<
    GetCardsByAssociationCardsByAssociationAssociationCodeGetResponses,
    GetCardsByAssociationCardsByAssociationAssociationCodeGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/cards/by-association/{association_code}",
    ...options,
  });

/**
 * Delete Card
 *
 * Delete a card by ID.
 */
export const deleteCardCardsCardIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteCardCardsCardIdDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteCardCardsCardIdDeleteResponses,
    DeleteCardCardsCardIdDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/cards/{card_id}",
    ...options,
  });

/**
 * Get All Decks
 *
 * Get all decks for the current user with full card data.
 */
export const getAllDecksDecksGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetAllDecksDecksGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetAllDecksDecksGetResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/decks",
    ...options,
  });

/**
 * Create Deck
 *
 * Create a new deck for the current user.
 */
export const createDeckDecksPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateDeckDecksPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateDeckDecksPostResponses,
    CreateDeckDecksPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/decks",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Deck Summaries
 *
 * Get lightweight deck summaries (without card details) for the current user.
 */
export const getDeckSummariesDecksSummariesGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetDeckSummariesDecksSummariesGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetDeckSummariesDecksSummariesGetResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/decks/summaries",
    ...options,
  });

/**
 * Delete Deck
 *
 * Delete a deck (only if owned by current user).
 */
export const deleteDeckDecksDeckIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteDeckDecksDeckIdDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteDeckDecksDeckIdDeleteResponses,
    DeleteDeckDecksDeckIdDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/decks/{deck_id}",
    ...options,
  });

/**
 * Get Deck
 *
 * Get a specific deck by ID (only if owned by current user).
 */
export const getDeckDecksDeckIdGet = <ThrowOnError extends boolean = false>(
  options: Options<GetDeckDecksDeckIdGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetDeckDecksDeckIdGetResponses,
    GetDeckDecksDeckIdGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/decks/{deck_id}",
    ...options,
  });

/**
 * Update Deck
 *
 * Update a deck (only if owned by current user).
 */
export const updateDeckDecksDeckIdPut = <ThrowOnError extends boolean = false>(
  options: Options<UpdateDeckDecksDeckIdPutData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    UpdateDeckDecksDeckIdPutResponses,
    UpdateDeckDecksDeckIdPutErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/decks/{deck_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Remove Card From Deck
 *
 * Remove a card from a deck.
 */
export const removeCardFromDeckDecksDeckIdCardsCardIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    RemoveCardFromDeckDecksDeckIdCardsCardIdDeleteData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).delete<
    RemoveCardFromDeckDecksDeckIdCardsCardIdDeleteResponses,
    RemoveCardFromDeckDecksDeckIdCardsCardIdDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/decks/{deck_id}/cards/{card_id}",
    ...options,
  });

/**
 * Add Card To Deck
 *
 * Add a card to a deck.
 */
export const addCardToDeckDecksDeckIdCardsCardIdPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AddCardToDeckDecksDeckIdCardsCardIdPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    AddCardToDeckDecksDeckIdCardsCardIdPostResponses,
    AddCardToDeckDecksDeckIdCardsCardIdPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/decks/{deck_id}/cards/{card_id}",
    ...options,
  });

/**
 * Root
 *
 * Health check endpoint.
 */
export const rootGet = <ThrowOnError extends boolean = false>(
  options?: Options<RootGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<RootGetResponses, unknown, ThrowOnError>({
    url: "/",
    ...options,
  });

/**
 * List Game Rooms
 *
 * List all available game rooms (HTTP endpoint for convenience).
 *
 * Returns rooms that haven't started yet.
 */
export const listGameRoomsGameRoomsGet = <ThrowOnError extends boolean = false>(
  options?: Options<ListGameRoomsGameRoomsGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListGameRoomsGameRoomsGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/game/rooms", ...options });
