// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  type Options as Options2,
  type TDataShape,
  urlSearchParamsBodySerializer,
} from "./client";
import { client } from "./client.gen";
import type {
  AddCardToDeckDecksDeckIdCardsCardIdPostData,
  AddCardToDeckDecksDeckIdCardsCardIdPostErrors,
  AddCardToDeckDecksDeckIdCardsCardIdPostResponses,
  CreateAbilitiesPostData,
  CreateAbilitiesPostErrors,
  CreateAbilitiesPostResponses,
  CreateAssociationsPostData,
  CreateAssociationsPostErrors,
  CreateAssociationsPostResponses,
  CreateAttackAttacksPostData,
  CreateAttackAttacksPostErrors,
  CreateAttackAttacksPostResponses,
  CreateCardCardsPostData,
  CreateCardCardsPostErrors,
  CreateCardCardsPostResponses,
  CreateCharactersPostData,
  CreateCharactersPostErrors,
  CreateCharactersPostResponses,
  CreateDeckDecksPostData,
  CreateDeckDecksPostErrors,
  CreateDeckDecksPostResponses,
  CreateElementsPostData,
  CreateElementsPostErrors,
  CreateElementsPostResponses,
  CreateTypesPostData,
  CreateTypesPostErrors,
  CreateTypesPostResponses,
  DeleteAbilitiesItemIdDeleteData,
  DeleteAbilitiesItemIdDeleteErrors,
  DeleteAbilitiesItemIdDeleteResponses,
  DeleteAssociationsItemIdDeleteData,
  DeleteAssociationsItemIdDeleteErrors,
  DeleteAssociationsItemIdDeleteResponses,
  DeleteAttackAttacksAttackIdDeleteData,
  DeleteAttackAttacksAttackIdDeleteErrors,
  DeleteAttackAttacksAttackIdDeleteResponses,
  DeleteCardCardsCardIdDeleteData,
  DeleteCardCardsCardIdDeleteErrors,
  DeleteCardCardsCardIdDeleteResponses,
  DeleteCharactersItemIdDeleteData,
  DeleteCharactersItemIdDeleteErrors,
  DeleteCharactersItemIdDeleteResponses,
  DeleteDeckDecksDeckIdDeleteData,
  DeleteDeckDecksDeckIdDeleteErrors,
  DeleteDeckDecksDeckIdDeleteResponses,
  DeleteElementsItemIdDeleteData,
  DeleteElementsItemIdDeleteErrors,
  DeleteElementsItemIdDeleteResponses,
  DeleteTypesItemIdDeleteData,
  DeleteTypesItemIdDeleteErrors,
  DeleteTypesItemIdDeleteResponses,
  DomainAttackDefinitionTypeGameWebsocketMessagesDomainAttackDefinitionGetData,
  DomainAttackDefinitionTypeGameWebsocketMessagesDomainAttackDefinitionGetResponses,
  DomainCardStatusTypeGameWebsocketMessagesDomainCardStatusGetData,
  DomainCardStatusTypeGameWebsocketMessagesDomainCardStatusGetResponses,
  DomainElementContributionTypeGameWebsocketMessagesDomainElementContributionGetData,
  DomainElementContributionTypeGameWebsocketMessagesDomainElementContributionGetResponses,
  DomainElementPoolTypeGameWebsocketMessagesDomainElementPoolGetData,
  DomainElementPoolTypeGameWebsocketMessagesDomainElementPoolGetResponses,
  DomainGameCardTypeGameWebsocketMessagesDomainGameCardGetData,
  DomainGameCardTypeGameWebsocketMessagesDomainGameCardGetResponses,
  DomainPlayerStateTypeGameWebsocketMessagesDomainPlayerStateGetData,
  DomainPlayerStateTypeGameWebsocketMessagesDomainPlayerStateGetResponses,
  DomainZoneStateTypeGameWebsocketMessagesDomainZoneStateGetData,
  DomainZoneStateTypeGameWebsocketMessagesDomainZoneStateGetResponses,
  GetAllAbilitiesGetData,
  GetAllAbilitiesGetResponses,
  GetAllAssociationsGetData,
  GetAllAssociationsGetResponses,
  GetAllAttacksAttacksGetData,
  GetAllAttacksAttacksGetResponses,
  GetAllCardsCardsGetData,
  GetAllCardsCardsGetResponses,
  GetAllCharactersGetData,
  GetAllCharactersGetResponses,
  GetAllDecksDecksGetData,
  GetAllDecksDecksGetResponses,
  GetAllElementsGetData,
  GetAllElementsGetResponses,
  GetAllTypesGetData,
  GetAllTypesGetResponses,
  GetAttackAttacksValueGetData,
  GetAttackAttacksValueGetErrors,
  GetAttackAttacksValueGetResponses,
  GetCardCardsValueGetData,
  GetCardCardsValueGetErrors,
  GetCardCardsValueGetResponses,
  GetCardsByAbilityCardsByAbilityAbilityCodeGetData,
  GetCardsByAbilityCardsByAbilityAbilityCodeGetErrors,
  GetCardsByAbilityCardsByAbilityAbilityCodeGetResponses,
  GetCardsByAssociationCardsByAssociationAssociationCodeGetData,
  GetCardsByAssociationCardsByAssociationAssociationCodeGetErrors,
  GetCardsByAssociationCardsByAssociationAssociationCodeGetResponses,
  GetCardsByAttackCardsByAttackAttackCodeGetData,
  GetCardsByAttackCardsByAttackAttackCodeGetErrors,
  GetCardsByAttackCardsByAttackAttackCodeGetResponses,
  GetDeckDecksDeckIdGetData,
  GetDeckDecksDeckIdGetErrors,
  GetDeckDecksDeckIdGetResponses,
  GetDeckSummariesDecksSummariesGetData,
  GetDeckSummariesDecksSummariesGetResponses,
  GetOneAbilitiesValueGetData,
  GetOneAbilitiesValueGetErrors,
  GetOneAbilitiesValueGetResponses,
  GetOneAssociationsValueGetData,
  GetOneAssociationsValueGetErrors,
  GetOneAssociationsValueGetResponses,
  GetOneCharactersValueGetData,
  GetOneCharactersValueGetErrors,
  GetOneCharactersValueGetResponses,
  GetOneElementsValueGetData,
  GetOneElementsValueGetErrors,
  GetOneElementsValueGetResponses,
  GetOneTypesValueGetData,
  GetOneTypesValueGetErrors,
  GetOneTypesValueGetResponses,
  ListRoomsGameRoomsGetData,
  ListRoomsGameRoomsGetResponses,
  LoginForAccessTokenAuthTokenPostData,
  LoginForAccessTokenAuthTokenPostErrors,
  LoginForAccessTokenAuthTokenPostResponses,
  ReadUsersMeAuthMeGetData,
  ReadUsersMeAuthMeGetResponses,
  RegisterUserAuthRegisterPostData,
  RegisterUserAuthRegisterPostErrors,
  RegisterUserAuthRegisterPostResponses,
  RemoveCardFromDeckDecksDeckIdCardsCardIdDeleteData,
  RemoveCardFromDeckDecksDeckIdCardsCardIdDeleteErrors,
  RemoveCardFromDeckDecksDeckIdCardsCardIdDeleteResponses,
  RootGetData,
  RootGetResponses,
  UpdateDeckDecksDeckIdPutData,
  UpdateDeckDecksDeckIdPutErrors,
  UpdateDeckDecksDeckIdPutResponses,
  WsActionResultTypeGameWebsocketMessagesActionResultGetData,
  WsActionResultTypeGameWebsocketMessagesActionResultGetResponses,
  WsActionTypeGameWebsocketMessagesActionPostData,
  WsActionTypeGameWebsocketMessagesActionPostErrors,
  WsActionTypeGameWebsocketMessagesActionPostResponses,
  WsConnectedTypeGameWebsocketMessagesConnectedGetData,
  WsConnectedTypeGameWebsocketMessagesConnectedGetResponses,
  WsErrorTypeGameWebsocketMessagesErrorGetData,
  WsErrorTypeGameWebsocketMessagesErrorGetResponses,
  WsGameCreatedTypeGameWebsocketMessagesGameCreatedGetData,
  WsGameCreatedTypeGameWebsocketMessagesGameCreatedGetResponses,
  WsGameJoinedTypeGameWebsocketMessagesGameJoinedGetData,
  WsGameJoinedTypeGameWebsocketMessagesGameJoinedGetResponses,
  WsGameLeftTypeGameWebsocketMessagesGameLeftGetData,
  WsGameLeftTypeGameWebsocketMessagesGameLeftGetResponses,
  WsGameStartedTypeGameWebsocketMessagesGameStartedGetData,
  WsGameStartedTypeGameWebsocketMessagesGameStartedGetResponses,
  WsGameStateTypeGameWebsocketMessagesGameStateGetData,
  WsGameStateTypeGameWebsocketMessagesGameStateGetResponses,
  WsGetStateTypeGameWebsocketMessagesGetStatePostData,
  WsGetStateTypeGameWebsocketMessagesGetStatePostErrors,
  WsGetStateTypeGameWebsocketMessagesGetStatePostResponses,
  WsGetValidActionsTypeGameWebsocketMessagesGetValidActionsPostData,
  WsGetValidActionsTypeGameWebsocketMessagesGetValidActionsPostErrors,
  WsGetValidActionsTypeGameWebsocketMessagesGetValidActionsPostResponses,
  WsJoinGameTypeGameWebsocketMessagesJoinGamePostData,
  WsJoinGameTypeGameWebsocketMessagesJoinGamePostErrors,
  WsJoinGameTypeGameWebsocketMessagesJoinGamePostResponses,
  WsLeaveGameTypeGameWebsocketMessagesLeaveGamePostData,
  WsLeaveGameTypeGameWebsocketMessagesLeaveGamePostErrors,
  WsLeaveGameTypeGameWebsocketMessagesLeaveGamePostResponses,
  WsListRoomsTypeGameWebsocketMessagesListRoomsPostData,
  WsListRoomsTypeGameWebsocketMessagesListRoomsPostErrors,
  WsListRoomsTypeGameWebsocketMessagesListRoomsPostResponses,
  WsPingTypeGameWebsocketMessagesPingPostData,
  WsPingTypeGameWebsocketMessagesPingPostErrors,
  WsPingTypeGameWebsocketMessagesPingPostResponses,
  WsPlayerJoinedTypeGameWebsocketMessagesPlayerJoinedGetData,
  WsPlayerJoinedTypeGameWebsocketMessagesPlayerJoinedGetResponses,
  WsPlayerLeftTypeGameWebsocketMessagesPlayerLeftGetData,
  WsPlayerLeftTypeGameWebsocketMessagesPlayerLeftGetResponses,
  WsPongTypeGameWebsocketMessagesPongGetData,
  WsPongTypeGameWebsocketMessagesPongGetResponses,
  WsRoomsListTypeGameWebsocketMessagesRoomsListGetData,
  WsRoomsListTypeGameWebsocketMessagesRoomsListGetResponses,
  WsValidActionsTypeGameWebsocketMessagesValidActionsGetData,
  WsValidActionsTypeGameWebsocketMessagesValidActionsGetResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Login For Access Token
 *
 * OAuth2 compatible token login, get an access token for future requests.
 */
export const loginForAccessTokenAuthTokenPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<LoginForAccessTokenAuthTokenPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    LoginForAccessTokenAuthTokenPostResponses,
    LoginForAccessTokenAuthTokenPostErrors,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    url: "/auth/token",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Register User
 *
 * Register a new user.
 */
export const registerUserAuthRegisterPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<RegisterUserAuthRegisterPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    RegisterUserAuthRegisterPostResponses,
    RegisterUserAuthRegisterPostErrors,
    ThrowOnError
  >({
    url: "/auth/register",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Read Users Me
 *
 * Get current authenticated user.
 */
export const readUsersMeAuthMeGet = <ThrowOnError extends boolean = false>(
  options?: Options<ReadUsersMeAuthMeGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ReadUsersMeAuthMeGetResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/auth/me",
    ...options,
  });

/**
 * Get All
 *
 * Get all records.
 */
export const getAllElementsGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetAllElementsGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetAllElementsGetResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/elements",
    ...options,
  });

/**
 * Create
 *
 * Create a new record.
 */
export const createElementsPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateElementsPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateElementsPostResponses,
    CreateElementsPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/elements",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get One
 *
 * Get record by ID or lookup field.
 */
export const getOneElementsValueGet = <ThrowOnError extends boolean = false>(
  options: Options<GetOneElementsValueGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetOneElementsValueGetResponses,
    GetOneElementsValueGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/elements/{value}",
    ...options,
  });

/**
 * Delete
 *
 * Delete a record by ID.
 */
export const deleteElementsItemIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteElementsItemIdDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteElementsItemIdDeleteResponses,
    DeleteElementsItemIdDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/elements/{item_id}",
    ...options,
  });

/**
 * Get All
 *
 * Get all records.
 */
export const getAllTypesGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetAllTypesGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetAllTypesGetResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/types",
    ...options,
  });

/**
 * Create
 *
 * Create a new record.
 */
export const createTypesPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateTypesPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateTypesPostResponses,
    CreateTypesPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/types",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get One
 *
 * Get record by ID or lookup field.
 */
export const getOneTypesValueGet = <ThrowOnError extends boolean = false>(
  options: Options<GetOneTypesValueGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetOneTypesValueGetResponses,
    GetOneTypesValueGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/types/{value}",
    ...options,
  });

/**
 * Delete
 *
 * Delete a record by ID.
 */
export const deleteTypesItemIdDelete = <ThrowOnError extends boolean = false>(
  options: Options<DeleteTypesItemIdDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteTypesItemIdDeleteResponses,
    DeleteTypesItemIdDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/types/{item_id}",
    ...options,
  });

/**
 * Get All
 *
 * Get all records.
 */
export const getAllCharactersGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetAllCharactersGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetAllCharactersGetResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/characters",
    ...options,
  });

/**
 * Create
 *
 * Create a new record.
 */
export const createCharactersPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateCharactersPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateCharactersPostResponses,
    CreateCharactersPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/characters",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get One
 *
 * Get record by ID or lookup field.
 */
export const getOneCharactersValueGet = <ThrowOnError extends boolean = false>(
  options: Options<GetOneCharactersValueGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetOneCharactersValueGetResponses,
    GetOneCharactersValueGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/characters/{value}",
    ...options,
  });

/**
 * Delete
 *
 * Delete a record by ID.
 */
export const deleteCharactersItemIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteCharactersItemIdDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteCharactersItemIdDeleteResponses,
    DeleteCharactersItemIdDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/characters/{item_id}",
    ...options,
  });

/**
 * Get All Attacks
 *
 * Get all attacks with enriched data.
 */
export const getAllAttacksAttacksGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetAllAttacksAttacksGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetAllAttacksAttacksGetResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/attacks",
    ...options,
  });

/**
 * Create Attack
 *
 * Create a new attack.
 */
export const createAttackAttacksPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateAttackAttacksPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateAttackAttacksPostResponses,
    CreateAttackAttacksPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/attacks",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Attack
 *
 * Get attack by code or name.
 */
export const getAttackAttacksValueGet = <ThrowOnError extends boolean = false>(
  options: Options<GetAttackAttacksValueGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetAttackAttacksValueGetResponses,
    GetAttackAttacksValueGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/attacks/{value}",
    ...options,
  });

/**
 * Delete Attack
 *
 * Delete an attack by ID.
 */
export const deleteAttackAttacksAttackIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteAttackAttacksAttackIdDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteAttackAttacksAttackIdDeleteResponses,
    DeleteAttackAttacksAttackIdDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/attacks/{attack_id}",
    ...options,
  });

/**
 * Get All
 *
 * Get all records.
 */
export const getAllAbilitiesGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetAllAbilitiesGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetAllAbilitiesGetResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/abilities",
    ...options,
  });

/**
 * Create
 *
 * Create a new record.
 */
export const createAbilitiesPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateAbilitiesPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateAbilitiesPostResponses,
    CreateAbilitiesPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/abilities",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get One
 *
 * Get record by ID or lookup field.
 */
export const getOneAbilitiesValueGet = <ThrowOnError extends boolean = false>(
  options: Options<GetOneAbilitiesValueGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetOneAbilitiesValueGetResponses,
    GetOneAbilitiesValueGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/abilities/{value}",
    ...options,
  });

/**
 * Delete
 *
 * Delete a record by ID.
 */
export const deleteAbilitiesItemIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteAbilitiesItemIdDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteAbilitiesItemIdDeleteResponses,
    DeleteAbilitiesItemIdDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/abilities/{item_id}",
    ...options,
  });

/**
 * Get All
 *
 * Get all records.
 */
export const getAllAssociationsGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetAllAssociationsGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetAllAssociationsGetResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/associations",
    ...options,
  });

/**
 * Create
 *
 * Create a new record.
 */
export const createAssociationsPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateAssociationsPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateAssociationsPostResponses,
    CreateAssociationsPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/associations",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get One
 *
 * Get record by ID or lookup field.
 */
export const getOneAssociationsValueGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetOneAssociationsValueGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetOneAssociationsValueGetResponses,
    GetOneAssociationsValueGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/associations/{value}",
    ...options,
  });

/**
 * Delete
 *
 * Delete a record by ID.
 */
export const deleteAssociationsItemIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteAssociationsItemIdDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteAssociationsItemIdDeleteResponses,
    DeleteAssociationsItemIdDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/associations/{item_id}",
    ...options,
  });

/**
 * Get All Cards
 *
 * Get all cards with enriched data.
 */
export const getAllCardsCardsGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetAllCardsCardsGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetAllCardsCardsGetResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/cards",
    ...options,
  });

/**
 * Create Card
 *
 * Create a new card.
 */
export const createCardCardsPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateCardCardsPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateCardCardsPostResponses,
    CreateCardCardsPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/cards",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Card
 *
 * Get card by code, handle, or name.
 */
export const getCardCardsValueGet = <ThrowOnError extends boolean = false>(
  options: Options<GetCardCardsValueGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetCardCardsValueGetResponses,
    GetCardCardsValueGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/cards/{value}",
    ...options,
  });

/**
 * Get Cards By Attack
 *
 * Get all cards that have a specific attack.
 */
export const getCardsByAttackCardsByAttackAttackCodeGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetCardsByAttackCardsByAttackAttackCodeGetData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).get<
    GetCardsByAttackCardsByAttackAttackCodeGetResponses,
    GetCardsByAttackCardsByAttackAttackCodeGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/cards/by-attack/{attack_code}",
    ...options,
  });

/**
 * Get Cards By Ability
 *
 * Get all cards that have a specific ability.
 */
export const getCardsByAbilityCardsByAbilityAbilityCodeGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetCardsByAbilityCardsByAbilityAbilityCodeGetData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).get<
    GetCardsByAbilityCardsByAbilityAbilityCodeGetResponses,
    GetCardsByAbilityCardsByAbilityAbilityCodeGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/cards/by-ability/{ability_code}",
    ...options,
  });

/**
 * Get Cards By Association
 *
 * Get all cards that have a specific association.
 */
export const getCardsByAssociationCardsByAssociationAssociationCodeGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetCardsByAssociationCardsByAssociationAssociationCodeGetData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).get<
    GetCardsByAssociationCardsByAssociationAssociationCodeGetResponses,
    GetCardsByAssociationCardsByAssociationAssociationCodeGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/cards/by-association/{association_code}",
    ...options,
  });

/**
 * Delete Card
 *
 * Delete a card by ID.
 */
export const deleteCardCardsCardIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteCardCardsCardIdDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteCardCardsCardIdDeleteResponses,
    DeleteCardCardsCardIdDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/cards/{card_id}",
    ...options,
  });

/**
 * Get All Decks
 *
 * Get all decks for the current user with full card data.
 */
export const getAllDecksDecksGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetAllDecksDecksGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetAllDecksDecksGetResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/decks",
    ...options,
  });

/**
 * Create Deck
 *
 * Create a new deck for the current user.
 */
export const createDeckDecksPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateDeckDecksPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateDeckDecksPostResponses,
    CreateDeckDecksPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/decks",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Deck Summaries
 *
 * Get lightweight deck summaries (without card details) for the current user.
 */
export const getDeckSummariesDecksSummariesGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetDeckSummariesDecksSummariesGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetDeckSummariesDecksSummariesGetResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/decks/summaries",
    ...options,
  });

/**
 * Delete Deck
 *
 * Delete a deck (only if owned by current user).
 */
export const deleteDeckDecksDeckIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteDeckDecksDeckIdDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteDeckDecksDeckIdDeleteResponses,
    DeleteDeckDecksDeckIdDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/decks/{deck_id}",
    ...options,
  });

/**
 * Get Deck
 *
 * Get a specific deck by ID (only if owned by current user).
 */
export const getDeckDecksDeckIdGet = <ThrowOnError extends boolean = false>(
  options: Options<GetDeckDecksDeckIdGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetDeckDecksDeckIdGetResponses,
    GetDeckDecksDeckIdGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/decks/{deck_id}",
    ...options,
  });

/**
 * Update Deck
 *
 * Update a deck (only if owned by current user).
 */
export const updateDeckDecksDeckIdPut = <ThrowOnError extends boolean = false>(
  options: Options<UpdateDeckDecksDeckIdPutData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    UpdateDeckDecksDeckIdPutResponses,
    UpdateDeckDecksDeckIdPutErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/decks/{deck_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Remove Card From Deck
 *
 * Remove a card from a deck.
 */
export const removeCardFromDeckDecksDeckIdCardsCardIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    RemoveCardFromDeckDecksDeckIdCardsCardIdDeleteData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).delete<
    RemoveCardFromDeckDecksDeckIdCardsCardIdDeleteResponses,
    RemoveCardFromDeckDecksDeckIdCardsCardIdDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/decks/{deck_id}/cards/{card_id}",
    ...options,
  });

/**
 * Add Card To Deck
 *
 * Add a card to a deck.
 */
export const addCardToDeckDecksDeckIdCardsCardIdPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AddCardToDeckDecksDeckIdCardsCardIdPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    AddCardToDeckDecksDeckIdCardsCardIdPostResponses,
    AddCardToDeckDecksDeckIdCardsCardIdPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/decks/{deck_id}/cards/{card_id}",
    ...options,
  });

/**
 * List Rooms
 *
 * List all available game rooms (HTTP endpoint for convenience).
 *
 * Returns rooms that haven't started yet.
 */
export const listRoomsGameRoomsGet = <ThrowOnError extends boolean = false>(
  options?: Options<ListRoomsGameRoomsGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListRoomsGameRoomsGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/game/rooms", ...options });

/**
 *  Ws Join Game Type
 *
 * WebSocket message type: join_game (dummy endpoint for type generation).
 */
export const wsJoinGameTypeGameWebsocketMessagesJoinGamePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    WsJoinGameTypeGameWebsocketMessagesJoinGamePostData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).post<
    WsJoinGameTypeGameWebsocketMessagesJoinGamePostResponses,
    WsJoinGameTypeGameWebsocketMessagesJoinGamePostErrors,
    ThrowOnError
  >({
    url: "/game/websocket-messages/join-game",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 *  Ws List Rooms Type
 *
 * WebSocket message type: list_rooms (dummy endpoint for type generation).
 */
export const wsListRoomsTypeGameWebsocketMessagesListRoomsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    WsListRoomsTypeGameWebsocketMessagesListRoomsPostData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).post<
    WsListRoomsTypeGameWebsocketMessagesListRoomsPostResponses,
    WsListRoomsTypeGameWebsocketMessagesListRoomsPostErrors,
    ThrowOnError
  >({
    url: "/game/websocket-messages/list-rooms",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 *  Ws Action Type
 *
 * WebSocket message type: action (dummy endpoint for type generation).
 */
export const wsActionTypeGameWebsocketMessagesActionPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    WsActionTypeGameWebsocketMessagesActionPostData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).post<
    WsActionTypeGameWebsocketMessagesActionPostResponses,
    WsActionTypeGameWebsocketMessagesActionPostErrors,
    ThrowOnError
  >({
    url: "/game/websocket-messages/action",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 *  Ws Get State Type
 *
 * WebSocket message type: get_state (dummy endpoint for type generation).
 */
export const wsGetStateTypeGameWebsocketMessagesGetStatePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    WsGetStateTypeGameWebsocketMessagesGetStatePostData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).post<
    WsGetStateTypeGameWebsocketMessagesGetStatePostResponses,
    WsGetStateTypeGameWebsocketMessagesGetStatePostErrors,
    ThrowOnError
  >({
    url: "/game/websocket-messages/get-state",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 *  Ws Get Valid Actions Type
 *
 * WebSocket message type: get_valid_actions (dummy endpoint for type generation).
 */
export const wsGetValidActionsTypeGameWebsocketMessagesGetValidActionsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    WsGetValidActionsTypeGameWebsocketMessagesGetValidActionsPostData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).post<
    WsGetValidActionsTypeGameWebsocketMessagesGetValidActionsPostResponses,
    WsGetValidActionsTypeGameWebsocketMessagesGetValidActionsPostErrors,
    ThrowOnError
  >({
    url: "/game/websocket-messages/get-valid-actions",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 *  Ws Leave Game Type
 *
 * WebSocket message type: leave_game (dummy endpoint for type generation).
 */
export const wsLeaveGameTypeGameWebsocketMessagesLeaveGamePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    WsLeaveGameTypeGameWebsocketMessagesLeaveGamePostData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).post<
    WsLeaveGameTypeGameWebsocketMessagesLeaveGamePostResponses,
    WsLeaveGameTypeGameWebsocketMessagesLeaveGamePostErrors,
    ThrowOnError
  >({
    url: "/game/websocket-messages/leave-game",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 *  Ws Ping Type
 *
 * WebSocket message type: ping (dummy endpoint for type generation).
 */
export const wsPingTypeGameWebsocketMessagesPingPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<WsPingTypeGameWebsocketMessagesPingPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    WsPingTypeGameWebsocketMessagesPingPostResponses,
    WsPingTypeGameWebsocketMessagesPingPostErrors,
    ThrowOnError
  >({
    url: "/game/websocket-messages/ping",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 *  Ws Connected Type
 *
 * WebSocket message type: connected (dummy endpoint for type generation).
 */
export const wsConnectedTypeGameWebsocketMessagesConnectedGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    WsConnectedTypeGameWebsocketMessagesConnectedGetData,
    ThrowOnError
  >,
) =>
  (options?.client ?? client).get<
    WsConnectedTypeGameWebsocketMessagesConnectedGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/game/websocket-messages/connected", ...options });

/**
 *  Ws Game Created Type
 *
 * WebSocket message type: game_created (dummy endpoint for type generation).
 */
export const wsGameCreatedTypeGameWebsocketMessagesGameCreatedGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    WsGameCreatedTypeGameWebsocketMessagesGameCreatedGetData,
    ThrowOnError
  >,
) =>
  (options?.client ?? client).get<
    WsGameCreatedTypeGameWebsocketMessagesGameCreatedGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/game/websocket-messages/game-created", ...options });

/**
 *  Ws Game Joined Type
 *
 * WebSocket message type: game_joined (dummy endpoint for type generation).
 */
export const wsGameJoinedTypeGameWebsocketMessagesGameJoinedGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    WsGameJoinedTypeGameWebsocketMessagesGameJoinedGetData,
    ThrowOnError
  >,
) =>
  (options?.client ?? client).get<
    WsGameJoinedTypeGameWebsocketMessagesGameJoinedGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/game/websocket-messages/game-joined", ...options });

/**
 *  Ws Player Joined Type
 *
 * WebSocket message type: player_joined (dummy endpoint for type generation).
 */
export const wsPlayerJoinedTypeGameWebsocketMessagesPlayerJoinedGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    WsPlayerJoinedTypeGameWebsocketMessagesPlayerJoinedGetData,
    ThrowOnError
  >,
) =>
  (options?.client ?? client).get<
    WsPlayerJoinedTypeGameWebsocketMessagesPlayerJoinedGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/game/websocket-messages/player-joined", ...options });

/**
 *  Ws Player Left Type
 *
 * WebSocket message type: player_left (dummy endpoint for type generation).
 */
export const wsPlayerLeftTypeGameWebsocketMessagesPlayerLeftGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    WsPlayerLeftTypeGameWebsocketMessagesPlayerLeftGetData,
    ThrowOnError
  >,
) =>
  (options?.client ?? client).get<
    WsPlayerLeftTypeGameWebsocketMessagesPlayerLeftGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/game/websocket-messages/player-left", ...options });

/**
 *  Ws Game Started Type
 *
 * WebSocket message type: game_started (dummy endpoint for type generation).
 */
export const wsGameStartedTypeGameWebsocketMessagesGameStartedGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    WsGameStartedTypeGameWebsocketMessagesGameStartedGetData,
    ThrowOnError
  >,
) =>
  (options?.client ?? client).get<
    WsGameStartedTypeGameWebsocketMessagesGameStartedGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/game/websocket-messages/game-started", ...options });

/**
 *  Ws Game State Type
 *
 * WebSocket message type: game_state (dummy endpoint for type generation).
 */
export const wsGameStateTypeGameWebsocketMessagesGameStateGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    WsGameStateTypeGameWebsocketMessagesGameStateGetData,
    ThrowOnError
  >,
) =>
  (options?.client ?? client).get<
    WsGameStateTypeGameWebsocketMessagesGameStateGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/game/websocket-messages/game-state", ...options });

/**
 *  Ws Action Result Type
 *
 * WebSocket message type: action_result (dummy endpoint for type generation).
 */
export const wsActionResultTypeGameWebsocketMessagesActionResultGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    WsActionResultTypeGameWebsocketMessagesActionResultGetData,
    ThrowOnError
  >,
) =>
  (options?.client ?? client).get<
    WsActionResultTypeGameWebsocketMessagesActionResultGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/game/websocket-messages/action-result", ...options });

/**
 *  Ws Valid Actions Type
 *
 * WebSocket message type: valid_actions (dummy endpoint for type generation).
 */
export const wsValidActionsTypeGameWebsocketMessagesValidActionsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    WsValidActionsTypeGameWebsocketMessagesValidActionsGetData,
    ThrowOnError
  >,
) =>
  (options?.client ?? client).get<
    WsValidActionsTypeGameWebsocketMessagesValidActionsGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/game/websocket-messages/valid-actions", ...options });

/**
 *  Ws Rooms List Type
 *
 * WebSocket message type: rooms_list (dummy endpoint for type generation).
 */
export const wsRoomsListTypeGameWebsocketMessagesRoomsListGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    WsRoomsListTypeGameWebsocketMessagesRoomsListGetData,
    ThrowOnError
  >,
) =>
  (options?.client ?? client).get<
    WsRoomsListTypeGameWebsocketMessagesRoomsListGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/game/websocket-messages/rooms-list", ...options });

/**
 *  Ws Game Left Type
 *
 * WebSocket message type: game_left (dummy endpoint for type generation).
 */
export const wsGameLeftTypeGameWebsocketMessagesGameLeftGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    WsGameLeftTypeGameWebsocketMessagesGameLeftGetData,
    ThrowOnError
  >,
) =>
  (options?.client ?? client).get<
    WsGameLeftTypeGameWebsocketMessagesGameLeftGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/game/websocket-messages/game-left", ...options });

/**
 *  Ws Error Type
 *
 * WebSocket message type: error (dummy endpoint for type generation).
 */
export const wsErrorTypeGameWebsocketMessagesErrorGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<WsErrorTypeGameWebsocketMessagesErrorGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    WsErrorTypeGameWebsocketMessagesErrorGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/game/websocket-messages/error", ...options });

/**
 *  Ws Pong Type
 *
 * WebSocket message type: pong (dummy endpoint for type generation).
 */
export const wsPongTypeGameWebsocketMessagesPongGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<WsPongTypeGameWebsocketMessagesPongGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    WsPongTypeGameWebsocketMessagesPongGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/game/websocket-messages/pong", ...options });

/**
 *  Domain Element Contribution Type
 *
 * Game domain type: ElementContribution (for type generation).
 */
export const domainElementContributionTypeGameWebsocketMessagesDomainElementContributionGet =
  <ThrowOnError extends boolean = false>(
    options?: Options<
      DomainElementContributionTypeGameWebsocketMessagesDomainElementContributionGetData,
      ThrowOnError
    >,
  ) =>
    (options?.client ?? client).get<
      DomainElementContributionTypeGameWebsocketMessagesDomainElementContributionGetResponses,
      unknown,
      ThrowOnError
    >({
      url: "/game/websocket-messages/domain/element-contribution",
      ...options,
    });

/**
 *  Domain Element Pool Type
 *
 * Game domain type: ElementPool (for type generation).
 */
export const domainElementPoolTypeGameWebsocketMessagesDomainElementPoolGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    DomainElementPoolTypeGameWebsocketMessagesDomainElementPoolGetData,
    ThrowOnError
  >,
) =>
  (options?.client ?? client).get<
    DomainElementPoolTypeGameWebsocketMessagesDomainElementPoolGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/game/websocket-messages/domain/element-pool", ...options });

/**
 *  Domain Attack Definition Type
 *
 * Game domain type: AttackDefinition (for type generation).
 */
export const domainAttackDefinitionTypeGameWebsocketMessagesDomainAttackDefinitionGet =
  <ThrowOnError extends boolean = false>(
    options?: Options<
      DomainAttackDefinitionTypeGameWebsocketMessagesDomainAttackDefinitionGetData,
      ThrowOnError
    >,
  ) =>
    (options?.client ?? client).get<
      DomainAttackDefinitionTypeGameWebsocketMessagesDomainAttackDefinitionGetResponses,
      unknown,
      ThrowOnError
    >({ url: "/game/websocket-messages/domain/attack-definition", ...options });

/**
 *  Domain Zone State Type
 *
 * Game domain type: ZoneState (for type generation).
 */
export const domainZoneStateTypeGameWebsocketMessagesDomainZoneStateGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    DomainZoneStateTypeGameWebsocketMessagesDomainZoneStateGetData,
    ThrowOnError
  >,
) =>
  (options?.client ?? client).get<
    DomainZoneStateTypeGameWebsocketMessagesDomainZoneStateGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/game/websocket-messages/domain/zone-state", ...options });

/**
 *  Domain Game Card Type
 *
 * Game domain type: GameCard (for type generation).
 */
export const domainGameCardTypeGameWebsocketMessagesDomainGameCardGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    DomainGameCardTypeGameWebsocketMessagesDomainGameCardGetData,
    ThrowOnError
  >,
) =>
  (options?.client ?? client).get<
    DomainGameCardTypeGameWebsocketMessagesDomainGameCardGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/game/websocket-messages/domain/game-card", ...options });

/**
 *  Domain Card Status Type
 *
 * Game domain type: CardStatus (for type generation).
 */
export const domainCardStatusTypeGameWebsocketMessagesDomainCardStatusGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    DomainCardStatusTypeGameWebsocketMessagesDomainCardStatusGetData,
    ThrowOnError
  >,
) =>
  (options?.client ?? client).get<
    DomainCardStatusTypeGameWebsocketMessagesDomainCardStatusGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/game/websocket-messages/domain/card-status", ...options });

/**
 *  Domain Player State Type
 *
 * Game domain type: PlayerState (for type generation).
 */
export const domainPlayerStateTypeGameWebsocketMessagesDomainPlayerStateGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    DomainPlayerStateTypeGameWebsocketMessagesDomainPlayerStateGetData,
    ThrowOnError
  >,
) =>
  (options?.client ?? client).get<
    DomainPlayerStateTypeGameWebsocketMessagesDomainPlayerStateGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/game/websocket-messages/domain/player-state", ...options });

/**
 * Root
 *
 * Health check endpoint.
 */
export const rootGet = <ThrowOnError extends boolean = false>(
  options?: Options<RootGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<RootGetResponses, unknown, ThrowOnError>({
    url: "/",
    ...options,
  });
