// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://localhost:8000" | (string & {});
};

/**
 * AbilityCreate
 *
 * Request body for creating an ability.
 */
export type AbilityCreate = {
  /**
   * Code
   */
  code: number;
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Type
   */
  type?: string | null;
};

/**
 * AbilityRead
 *
 * Response model for an ability.
 */
export type AbilityRead = {
  /**
   * Id
   */
  id: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Code
   */
  code: number;
  /**
   * Name
   */
  name: string;
  /**
   * Handle
   */
  handle: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Type
   */
  type?: string | null;
};

/**
 * AssociationCreate
 *
 * Request body for creating an association.
 */
export type AssociationCreate = {
  /**
   * Code
   */
  code: number;
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
};

/**
 * AssociationRead
 *
 * Response model for an association.
 */
export type AssociationRead = {
  /**
   * Id
   */
  id: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Code
   */
  code: number;
  /**
   * Name
   */
  name: string;
  /**
   * Handle
   */
  handle: string;
  /**
   * Description
   */
  description?: string | null;
};

/**
 * AttackCreate
 *
 * Request body for creating an attack.
 */
export type AttackCreate = {
  /**
   * Code
   */
  code: number;
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Damage
   */
  damage?: number | null;
  /**
   * Type
   */
  type?: string | null;
  /**
   * Element Id
   */
  element_id?: number | null;
  /**
   * Dice Rolls
   */
  dice_rolls?: number | null;
  /**
   * Necessary Force
   */
  necessary_force?: Array<{
    [key: string]: unknown;
  }> | null;
  /**
   * Effect
   */
  effect?: string | null;
};

/**
 * AttackReadWithElement
 *
 * Response model for an attack with element details.
 */
export type AttackReadWithElement = {
  /**
   * Id
   */
  id: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Code
   */
  code: number;
  /**
   * Name
   */
  name: string;
  /**
   * Handle
   */
  handle: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Damage
   */
  damage?: number | null;
  /**
   * Type
   */
  type?: string | null;
  /**
   * Element Id
   */
  element_id?: number | null;
  /**
   * Dice Rolls
   */
  dice_rolls?: number | null;
  /**
   * Necessary Force
   */
  necessary_force?: Array<{
    [key: string]: unknown;
  }> | null;
  /**
   * Effect
   */
  effect?: string | null;
  element?: ElementRead | null;
  /**
   * Strengths
   */
  strengths?: Array<number> | null;
  /**
   * Weaknesses
   */
  weaknesses?: Array<number> | null;
};

/**
 * CardCreate
 *
 * Request body for creating a card.
 */
export type CardCreate = {
  /**
   * Code
   */
  code: number;
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Image
   */
  image?: string | null;
  /**
   * Overlay Image
   */
  overlay_image?: string | null;
  /**
   * Is Evolution Id
   */
  is_evolution_id?: number | null;
  /**
   * First Element Id
   */
  first_element_id?: number | null;
  /**
   * Second Element Id
   */
  second_element_id?: number | null;
  /**
   * Type Id
   */
  type_id?: number | null;
  /**
   * Character Id
   */
  character_id?: number | null;
  /**
   * First Attack Id
   */
  first_attack_id?: number | null;
  /**
   * Second Attack Id
   */
  second_attack_id?: number | null;
  /**
   * Ability Id
   */
  ability_id?: number | null;
  /**
   * Association Id
   */
  association_id?: number | null;
  /**
   * Health
   */
  health?: number | null;
  /**
   * Physical Defence
   */
  physical_defence?: number | null;
  /**
   * Magic Defence
   */
  magic_defence?: number | null;
  /**
   * Forces
   */
  forces?: {
    [key: string]: unknown;
  } | null;
};

/**
 * CardRead
 *
 * Response model for a card (lightweight).
 */
export type CardRead = {
  /**
   * Id
   */
  id: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Code
   */
  code: number;
  /**
   * Name
   */
  name: string;
  /**
   * Handle
   */
  handle: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Image
   */
  image?: string | null;
  /**
   * Overlay Image
   */
  overlay_image?: string | null;
  /**
   * Health
   */
  health?: number | null;
  /**
   * Physical Defence
   */
  physical_defence?: number | null;
  /**
   * Magic Defence
   */
  magic_defence?: number | null;
  /**
   * Forces
   */
  forces?: Array<{
    [key: string]: unknown;
  }> | null;
  /**
   * Is Evolution Id
   */
  is_evolution_id?: number | null;
  /**
   * First Element Id
   */
  first_element_id?: number | null;
  /**
   * Second Element Id
   */
  second_element_id?: number | null;
  /**
   * Type Id
   */
  type_id?: number | null;
  /**
   * Character Id
   */
  character_id?: number | null;
  /**
   * First Attack Id
   */
  first_attack_id?: number | null;
  /**
   * Second Attack Id
   */
  second_attack_id?: number | null;
  /**
   * Ability Id
   */
  ability_id?: number | null;
  /**
   * Association Id
   */
  association_id?: number | null;
};

/**
 * CardReadWithRelations
 *
 * Response model for a card with all relationships.
 */
export type CardReadWithRelations = {
  /**
   * Id
   */
  id: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Code
   */
  code: number;
  /**
   * Name
   */
  name: string;
  /**
   * Handle
   */
  handle: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Image
   */
  image?: string | null;
  /**
   * Overlay Image
   */
  overlay_image?: string | null;
  /**
   * Health
   */
  health?: number | null;
  /**
   * Physical Defence
   */
  physical_defence?: number | null;
  /**
   * Magic Defence
   */
  magic_defence?: number | null;
  /**
   * Forces
   */
  forces?: Array<{
    [key: string]: unknown;
  }> | null;
  /**
   * Is Evolution Id
   */
  is_evolution_id?: number | null;
  /**
   * First Element Id
   */
  first_element_id?: number | null;
  /**
   * Second Element Id
   */
  second_element_id?: number | null;
  /**
   * Type Id
   */
  type_id?: number | null;
  /**
   * Character Id
   */
  character_id?: number | null;
  /**
   * First Attack Id
   */
  first_attack_id?: number | null;
  /**
   * Second Attack Id
   */
  second_attack_id?: number | null;
  /**
   * Ability Id
   */
  ability_id?: number | null;
  /**
   * Association Id
   */
  association_id?: number | null;
  first_element?: ElementRead | null;
  second_element?: ElementRead | null;
  type?: TypeRead | null;
  character?: CharacterRead | null;
  first_attack?: AttackReadWithElement | null;
  second_attack?: AttackReadWithElement | null;
  ability?: AbilityRead | null;
  association?: AssociationRead | null;
  is_evolution?: CardRead | null;
  /**
   * Next Evolutions
   */
  next_evolutions?: Array<CardRead> | null;
  /**
   * Strengths
   */
  strengths?: Array<number> | null;
  /**
   * Weaknesses
   */
  weaknesses?: Array<number> | null;
};

/**
 * CharacterCreate
 *
 * Request body for creating a character.
 */
export type CharacterCreate = {
  /**
   * Label
   */
  label: string;
  /**
   * Icon
   */
  icon?: string | null;
};

/**
 * CharacterRead
 *
 * Response model for a character.
 */
export type CharacterRead = {
  /**
   * Id
   */
  id: number;
  /**
   * Label
   */
  label: string;
  /**
   * Icon
   */
  icon?: string | null;
};

/**
 * ElementCreate
 *
 * Request body for creating an element.
 */
export type ElementCreate = {
  /**
   * Label
   */
  label: string;
  /**
   * Icon
   */
  icon?: string | null;
  /**
   * Color
   */
  color?: string | null;
  /**
   * Strengths
   */
  strengths?: Array<number> | null;
  /**
   * Weaknesses
   */
  weaknesses?: Array<number> | null;
};

/**
 * ElementRead
 *
 * Response model for an element.
 */
export type ElementRead = {
  /**
   * Id
   */
  id: number;
  /**
   * Label
   */
  label: string;
  /**
   * Icon
   */
  icon?: string | null;
  /**
   * Color
   */
  color?: string | null;
  /**
   * Strengths
   */
  strengths?: Array<number> | null;
  /**
   * Weaknesses
   */
  weaknesses?: Array<number> | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * TypeCreate
 *
 * Request body for creating a type.
 */
export type TypeCreate = {
  /**
   * Label
   */
  label: string;
  /**
   * Icon
   */
  icon?: string | null;
};

/**
 * TypeRead
 *
 * Response model for a type.
 */
export type TypeRead = {
  /**
   * Id
   */
  id: number;
  /**
   * Label
   */
  label: string;
  /**
   * Icon
   */
  icon?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

export type GetAllElementsElementsGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/elements";
};

export type GetAllElementsElementsGetResponses = {
  /**
   * Response Get All Elements Elements Get
   *
   * Successful Response
   */
  200: Array<ElementRead>;
};

export type GetAllElementsElementsGetResponse =
  GetAllElementsElementsGetResponses[keyof GetAllElementsElementsGetResponses];

export type CreateElementElementsPostData = {
  body: ElementCreate;
  path?: never;
  query?: never;
  url: "/elements";
};

export type CreateElementElementsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateElementElementsPostError =
  CreateElementElementsPostErrors[keyof CreateElementElementsPostErrors];

export type CreateElementElementsPostResponses = {
  /**
   * Successful Response
   */
  201: ElementRead;
};

export type CreateElementElementsPostResponse =
  CreateElementElementsPostResponses[keyof CreateElementElementsPostResponses];

export type GetElementElementsValueGetData = {
  body?: never;
  path: {
    /**
     * Value
     */
    value: string;
  };
  query?: never;
  url: "/elements/{value}";
};

export type GetElementElementsValueGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetElementElementsValueGetError =
  GetElementElementsValueGetErrors[keyof GetElementElementsValueGetErrors];

export type GetElementElementsValueGetResponses = {
  /**
   * Successful Response
   */
  200: ElementRead;
};

export type GetElementElementsValueGetResponse =
  GetElementElementsValueGetResponses[keyof GetElementElementsValueGetResponses];

export type DeleteElementElementsElementIdDeleteData = {
  body?: never;
  path: {
    /**
     * Element Id
     */
    element_id: number;
  };
  query?: never;
  url: "/elements/{element_id}";
};

export type DeleteElementElementsElementIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteElementElementsElementIdDeleteError =
  DeleteElementElementsElementIdDeleteErrors[keyof DeleteElementElementsElementIdDeleteErrors];

export type DeleteElementElementsElementIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetAllTypesTypesGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/types";
};

export type GetAllTypesTypesGetResponses = {
  /**
   * Response Get All Types Types Get
   *
   * Successful Response
   */
  200: Array<TypeRead>;
};

export type GetAllTypesTypesGetResponse =
  GetAllTypesTypesGetResponses[keyof GetAllTypesTypesGetResponses];

export type CreateTypeTypesPostData = {
  body: TypeCreate;
  path?: never;
  query?: never;
  url: "/types";
};

export type CreateTypeTypesPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateTypeTypesPostError =
  CreateTypeTypesPostErrors[keyof CreateTypeTypesPostErrors];

export type CreateTypeTypesPostResponses = {
  /**
   * Successful Response
   */
  201: TypeRead;
};

export type CreateTypeTypesPostResponse =
  CreateTypeTypesPostResponses[keyof CreateTypeTypesPostResponses];

export type GetTypeTypesValueGetData = {
  body?: never;
  path: {
    /**
     * Value
     */
    value: string;
  };
  query?: never;
  url: "/types/{value}";
};

export type GetTypeTypesValueGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetTypeTypesValueGetError =
  GetTypeTypesValueGetErrors[keyof GetTypeTypesValueGetErrors];

export type GetTypeTypesValueGetResponses = {
  /**
   * Successful Response
   */
  200: TypeRead;
};

export type GetTypeTypesValueGetResponse =
  GetTypeTypesValueGetResponses[keyof GetTypeTypesValueGetResponses];

export type DeleteTypeTypesTypeIdDeleteData = {
  body?: never;
  path: {
    /**
     * Type Id
     */
    type_id: number;
  };
  query?: never;
  url: "/types/{type_id}";
};

export type DeleteTypeTypesTypeIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteTypeTypesTypeIdDeleteError =
  DeleteTypeTypesTypeIdDeleteErrors[keyof DeleteTypeTypesTypeIdDeleteErrors];

export type DeleteTypeTypesTypeIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetAllCharactersCharactersGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/characters";
};

export type GetAllCharactersCharactersGetResponses = {
  /**
   * Response Get All Characters Characters Get
   *
   * Successful Response
   */
  200: Array<CharacterRead>;
};

export type GetAllCharactersCharactersGetResponse =
  GetAllCharactersCharactersGetResponses[keyof GetAllCharactersCharactersGetResponses];

export type CreateCharacterCharactersPostData = {
  body: CharacterCreate;
  path?: never;
  query?: never;
  url: "/characters";
};

export type CreateCharacterCharactersPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateCharacterCharactersPostError =
  CreateCharacterCharactersPostErrors[keyof CreateCharacterCharactersPostErrors];

export type CreateCharacterCharactersPostResponses = {
  /**
   * Successful Response
   */
  201: CharacterRead;
};

export type CreateCharacterCharactersPostResponse =
  CreateCharacterCharactersPostResponses[keyof CreateCharacterCharactersPostResponses];

export type GetCharacterCharactersValueGetData = {
  body?: never;
  path: {
    /**
     * Value
     */
    value: string;
  };
  query?: never;
  url: "/characters/{value}";
};

export type GetCharacterCharactersValueGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetCharacterCharactersValueGetError =
  GetCharacterCharactersValueGetErrors[keyof GetCharacterCharactersValueGetErrors];

export type GetCharacterCharactersValueGetResponses = {
  /**
   * Successful Response
   */
  200: CharacterRead;
};

export type GetCharacterCharactersValueGetResponse =
  GetCharacterCharactersValueGetResponses[keyof GetCharacterCharactersValueGetResponses];

export type DeleteCharacterCharactersCharacterIdDeleteData = {
  body?: never;
  path: {
    /**
     * Character Id
     */
    character_id: number;
  };
  query?: never;
  url: "/characters/{character_id}";
};

export type DeleteCharacterCharactersCharacterIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteCharacterCharactersCharacterIdDeleteError =
  DeleteCharacterCharactersCharacterIdDeleteErrors[keyof DeleteCharacterCharactersCharacterIdDeleteErrors];

export type DeleteCharacterCharactersCharacterIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetAllAttacksAttacksGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/attacks";
};

export type GetAllAttacksAttacksGetResponses = {
  /**
   * Response Get All Attacks Attacks Get
   *
   * Successful Response
   */
  200: Array<AttackReadWithElement>;
};

export type GetAllAttacksAttacksGetResponse =
  GetAllAttacksAttacksGetResponses[keyof GetAllAttacksAttacksGetResponses];

export type CreateAttackAttacksPostData = {
  body: AttackCreate;
  path?: never;
  query?: never;
  url: "/attacks";
};

export type CreateAttackAttacksPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateAttackAttacksPostError =
  CreateAttackAttacksPostErrors[keyof CreateAttackAttacksPostErrors];

export type CreateAttackAttacksPostResponses = {
  /**
   * Successful Response
   */
  201: AttackReadWithElement;
};

export type CreateAttackAttacksPostResponse =
  CreateAttackAttacksPostResponses[keyof CreateAttackAttacksPostResponses];

export type GetAttackAttacksValueGetData = {
  body?: never;
  path: {
    /**
     * Value
     */
    value: string;
  };
  query?: never;
  url: "/attacks/{value}";
};

export type GetAttackAttacksValueGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetAttackAttacksValueGetError =
  GetAttackAttacksValueGetErrors[keyof GetAttackAttacksValueGetErrors];

export type GetAttackAttacksValueGetResponses = {
  /**
   * Successful Response
   */
  200: AttackReadWithElement;
};

export type GetAttackAttacksValueGetResponse =
  GetAttackAttacksValueGetResponses[keyof GetAttackAttacksValueGetResponses];

export type DeleteAttackAttacksAttackIdDeleteData = {
  body?: never;
  path: {
    /**
     * Attack Id
     */
    attack_id: number;
  };
  query?: never;
  url: "/attacks/{attack_id}";
};

export type DeleteAttackAttacksAttackIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteAttackAttacksAttackIdDeleteError =
  DeleteAttackAttacksAttackIdDeleteErrors[keyof DeleteAttackAttacksAttackIdDeleteErrors];

export type DeleteAttackAttacksAttackIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetAllAbilitiesAbilitiesGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/abilities";
};

export type GetAllAbilitiesAbilitiesGetResponses = {
  /**
   * Response Get All Abilities Abilities Get
   *
   * Successful Response
   */
  200: Array<AbilityRead>;
};

export type GetAllAbilitiesAbilitiesGetResponse =
  GetAllAbilitiesAbilitiesGetResponses[keyof GetAllAbilitiesAbilitiesGetResponses];

export type CreateAbilityAbilitiesPostData = {
  body: AbilityCreate;
  path?: never;
  query?: never;
  url: "/abilities";
};

export type CreateAbilityAbilitiesPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateAbilityAbilitiesPostError =
  CreateAbilityAbilitiesPostErrors[keyof CreateAbilityAbilitiesPostErrors];

export type CreateAbilityAbilitiesPostResponses = {
  /**
   * Successful Response
   */
  201: AbilityRead;
};

export type CreateAbilityAbilitiesPostResponse =
  CreateAbilityAbilitiesPostResponses[keyof CreateAbilityAbilitiesPostResponses];

export type GetAbilityAbilitiesValueGetData = {
  body?: never;
  path: {
    /**
     * Value
     */
    value: string;
  };
  query?: never;
  url: "/abilities/{value}";
};

export type GetAbilityAbilitiesValueGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetAbilityAbilitiesValueGetError =
  GetAbilityAbilitiesValueGetErrors[keyof GetAbilityAbilitiesValueGetErrors];

export type GetAbilityAbilitiesValueGetResponses = {
  /**
   * Successful Response
   */
  200: AbilityRead;
};

export type GetAbilityAbilitiesValueGetResponse =
  GetAbilityAbilitiesValueGetResponses[keyof GetAbilityAbilitiesValueGetResponses];

export type DeleteAbilityAbilitiesAbilityIdDeleteData = {
  body?: never;
  path: {
    /**
     * Ability Id
     */
    ability_id: number;
  };
  query?: never;
  url: "/abilities/{ability_id}";
};

export type DeleteAbilityAbilitiesAbilityIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteAbilityAbilitiesAbilityIdDeleteError =
  DeleteAbilityAbilitiesAbilityIdDeleteErrors[keyof DeleteAbilityAbilitiesAbilityIdDeleteErrors];

export type DeleteAbilityAbilitiesAbilityIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetAllAssociationsAssociationsGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/associations";
};

export type GetAllAssociationsAssociationsGetResponses = {
  /**
   * Response Get All Associations Associations Get
   *
   * Successful Response
   */
  200: Array<AssociationRead>;
};

export type GetAllAssociationsAssociationsGetResponse =
  GetAllAssociationsAssociationsGetResponses[keyof GetAllAssociationsAssociationsGetResponses];

export type CreateAssociationAssociationsPostData = {
  body: AssociationCreate;
  path?: never;
  query?: never;
  url: "/associations";
};

export type CreateAssociationAssociationsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateAssociationAssociationsPostError =
  CreateAssociationAssociationsPostErrors[keyof CreateAssociationAssociationsPostErrors];

export type CreateAssociationAssociationsPostResponses = {
  /**
   * Successful Response
   */
  201: AssociationRead;
};

export type CreateAssociationAssociationsPostResponse =
  CreateAssociationAssociationsPostResponses[keyof CreateAssociationAssociationsPostResponses];

export type GetAssociationAssociationsValueGetData = {
  body?: never;
  path: {
    /**
     * Value
     */
    value: string;
  };
  query?: never;
  url: "/associations/{value}";
};

export type GetAssociationAssociationsValueGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetAssociationAssociationsValueGetError =
  GetAssociationAssociationsValueGetErrors[keyof GetAssociationAssociationsValueGetErrors];

export type GetAssociationAssociationsValueGetResponses = {
  /**
   * Successful Response
   */
  200: AssociationRead;
};

export type GetAssociationAssociationsValueGetResponse =
  GetAssociationAssociationsValueGetResponses[keyof GetAssociationAssociationsValueGetResponses];

export type DeleteAssociationAssociationsAssociationIdDeleteData = {
  body?: never;
  path: {
    /**
     * Association Id
     */
    association_id: number;
  };
  query?: never;
  url: "/associations/{association_id}";
};

export type DeleteAssociationAssociationsAssociationIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteAssociationAssociationsAssociationIdDeleteError =
  DeleteAssociationAssociationsAssociationIdDeleteErrors[keyof DeleteAssociationAssociationsAssociationIdDeleteErrors];

export type DeleteAssociationAssociationsAssociationIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetAllCardsCardsGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/cards";
};

export type GetAllCardsCardsGetResponses = {
  /**
   * Response Get All Cards Cards Get
   *
   * Successful Response
   */
  200: Array<CardReadWithRelations>;
};

export type GetAllCardsCardsGetResponse =
  GetAllCardsCardsGetResponses[keyof GetAllCardsCardsGetResponses];

export type CreateCardCardsPostData = {
  body: CardCreate;
  path?: never;
  query?: never;
  url: "/cards";
};

export type CreateCardCardsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateCardCardsPostError =
  CreateCardCardsPostErrors[keyof CreateCardCardsPostErrors];

export type CreateCardCardsPostResponses = {
  /**
   * Successful Response
   */
  201: CardReadWithRelations;
};

export type CreateCardCardsPostResponse =
  CreateCardCardsPostResponses[keyof CreateCardCardsPostResponses];

export type GetCardCardsValueGetData = {
  body?: never;
  path: {
    /**
     * Value
     */
    value: string;
  };
  query?: never;
  url: "/cards/{value}";
};

export type GetCardCardsValueGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetCardCardsValueGetError =
  GetCardCardsValueGetErrors[keyof GetCardCardsValueGetErrors];

export type GetCardCardsValueGetResponses = {
  /**
   * Response Get Card Cards  Value  Get
   *
   * Successful Response
   */
  200: Array<CardReadWithRelations>;
};

export type GetCardCardsValueGetResponse =
  GetCardCardsValueGetResponses[keyof GetCardCardsValueGetResponses];

export type GetCardsByAttackCardsByAttackAttackCodeGetData = {
  body?: never;
  path: {
    /**
     * Attack Code
     */
    attack_code: number;
  };
  query?: never;
  url: "/cards/by-attack/{attack_code}";
};

export type GetCardsByAttackCardsByAttackAttackCodeGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetCardsByAttackCardsByAttackAttackCodeGetError =
  GetCardsByAttackCardsByAttackAttackCodeGetErrors[keyof GetCardsByAttackCardsByAttackAttackCodeGetErrors];

export type GetCardsByAttackCardsByAttackAttackCodeGetResponses = {
  /**
   * Response Get Cards By Attack Cards By Attack  Attack Code  Get
   *
   * Successful Response
   */
  200: Array<CardReadWithRelations>;
};

export type GetCardsByAttackCardsByAttackAttackCodeGetResponse =
  GetCardsByAttackCardsByAttackAttackCodeGetResponses[keyof GetCardsByAttackCardsByAttackAttackCodeGetResponses];

export type GetCardsByAbilityCardsByAbilityAbilityCodeGetData = {
  body?: never;
  path: {
    /**
     * Ability Code
     */
    ability_code: number;
  };
  query?: never;
  url: "/cards/by-ability/{ability_code}";
};

export type GetCardsByAbilityCardsByAbilityAbilityCodeGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetCardsByAbilityCardsByAbilityAbilityCodeGetError =
  GetCardsByAbilityCardsByAbilityAbilityCodeGetErrors[keyof GetCardsByAbilityCardsByAbilityAbilityCodeGetErrors];

export type GetCardsByAbilityCardsByAbilityAbilityCodeGetResponses = {
  /**
   * Response Get Cards By Ability Cards By Ability  Ability Code  Get
   *
   * Successful Response
   */
  200: Array<CardReadWithRelations>;
};

export type GetCardsByAbilityCardsByAbilityAbilityCodeGetResponse =
  GetCardsByAbilityCardsByAbilityAbilityCodeGetResponses[keyof GetCardsByAbilityCardsByAbilityAbilityCodeGetResponses];

export type GetCardsByAssociationCardsByAssociationAssociationCodeGetData = {
  body?: never;
  path: {
    /**
     * Association Code
     */
    association_code: number;
  };
  query?: never;
  url: "/cards/by-association/{association_code}";
};

export type GetCardsByAssociationCardsByAssociationAssociationCodeGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetCardsByAssociationCardsByAssociationAssociationCodeGetError =
  GetCardsByAssociationCardsByAssociationAssociationCodeGetErrors[keyof GetCardsByAssociationCardsByAssociationAssociationCodeGetErrors];

export type GetCardsByAssociationCardsByAssociationAssociationCodeGetResponses =
  {
    /**
     * Response Get Cards By Association Cards By Association  Association Code  Get
     *
     * Successful Response
     */
    200: Array<CardReadWithRelations>;
  };

export type GetCardsByAssociationCardsByAssociationAssociationCodeGetResponse =
  GetCardsByAssociationCardsByAssociationAssociationCodeGetResponses[keyof GetCardsByAssociationCardsByAssociationAssociationCodeGetResponses];

export type DeleteCardCardsCardIdDeleteData = {
  body?: never;
  path: {
    /**
     * Card Id
     */
    card_id: number;
  };
  query?: never;
  url: "/cards/{card_id}";
};

export type DeleteCardCardsCardIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteCardCardsCardIdDeleteError =
  DeleteCardCardsCardIdDeleteErrors[keyof DeleteCardCardsCardIdDeleteErrors];

export type DeleteCardCardsCardIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type RootGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/";
};

export type RootGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};
