// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://localhost:8000" | (string & {});
};

/**
 * AbilityCreate
 */
export type AbilityCreate = {
  /**
   * Code
   */
  code: number;
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Type
   */
  type?: string | null;
};

/**
 * AbilityRead
 */
export type AbilityRead = {
  /**
   * Code
   */
  code: number;
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Type
   */
  type?: string | null;
  /**
   * Id
   */
  id: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Handle
   */
  handle: string;
};

/**
 * ActionData
 *
 * Data for action message.
 */
export type ActionData = {
  /**
   * Action Type
   */
  action_type: string;
  /**
   * Card Id
   */
  card_id?: string | null;
  /**
   * Card Ids
   */
  card_ids?: Array<string>;
  /**
   * Count
   */
  count?: number;
  /**
   * Target Id
   */
  target_id?: string | null;
  /**
   * Attacker Id
   */
  attacker_id?: string | null;
  /**
   * Attack Id
   */
  attack_id?: string | null;
  /**
   * Supporting Card Id
   */
  supporting_card_id?: string | null;
  /**
   * Attacking Card Id
   */
  attacking_card_id?: string | null;
  /**
   * Swaps
   */
  swaps?: Array<{
    [key: string]: unknown;
  }>;
  /**
   * Association Card Id
   */
  association_card_id?: string | null;
  /**
   * Evolution Card Id
   */
  evolution_card_id?: string | null;
};

/**
 * ActionMessage
 *
 * Perform a game action.
 */
export type ActionMessage = {
  data: ActionData;
};

/**
 * ActionResultData
 *
 * Data for action_result message.
 */
export type ActionResultData = {
  /**
   * Success
   */
  success: boolean;
  /**
   * Error
   */
  error?: string | null;
  /**
   * Events
   */
  events: Array<{
    [key: string]: unknown;
  }>;
  /**
   * Game Over
   */
  game_over: boolean;
  /**
   * Winner Id
   */
  winner_id?: string | null;
  /**
   * Game State
   */
  game_state?: {
    [key: string]: unknown;
  } | null;
  /**
   * Valid Actions
   */
  valid_actions?: Array<{
    [key: string]: unknown;
  }>;
};

/**
 * ActionResultMessage
 *
 * Result of an action.
 */
export type ActionResultMessage = {
  data: ActionResultData;
};

/**
 * AssociationCreate
 */
export type AssociationCreate = {
  /**
   * Code
   */
  code: number;
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
};

/**
 * AssociationRead
 */
export type AssociationRead = {
  /**
   * Code
   */
  code: number;
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Id
   */
  id: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Handle
   */
  handle: string;
};

/**
 * AttackCreate
 */
export type AttackCreate = {
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Damage
   */
  damage?: number | null;
  /**
   * Effect
   */
  effect?: string | null;
  /**
   * Dice Rolls
   */
  dice_rolls?: number | null;
  /**
   * Code
   */
  code: number;
  /**
   * Type
   */
  type?: string | null;
  /**
   * Necessary Force
   */
  necessary_force?: Array<{
    [key: string]: unknown;
  }> | null;
  /**
   * Element Id
   */
  element_id?: number | null;
};

/**
 * AttackReadWithElement
 */
export type AttackReadWithElement = {
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Damage
   */
  damage?: number | null;
  /**
   * Effect
   */
  effect?: string | null;
  /**
   * Dice Rolls
   */
  dice_rolls?: number | null;
  /**
   * Code
   */
  code: number;
  /**
   * Type
   */
  type?: string | null;
  /**
   * Necessary Force
   */
  necessary_force?: Array<{
    [key: string]: unknown;
  }> | null;
  /**
   * Id
   */
  id: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Handle
   */
  handle: string;
  /**
   * Element Id
   */
  element_id?: number | null;
  element?: ElementRead | null;
  /**
   * Strengths
   */
  strengths?: Array<number> | null;
  /**
   * Weaknesses
   */
  weaknesses?: Array<number> | null;
};

/**
 * Body_login_for_access_token_auth_token_post
 */
export type BodyLoginForAccessTokenAuthTokenPost = {
  /**
   * Grant Type
   */
  grant_type?: string | null;
  /**
   * Username
   */
  username: string;
  /**
   * Password
   */
  password: string;
  /**
   * Scope
   */
  scope?: string;
  /**
   * Client Id
   */
  client_id?: string | null;
  /**
   * Client Secret
   */
  client_secret?: string | null;
};

/**
 * CardCreate
 */
export type CardCreate = {
  /**
   * Is Evolution Id
   */
  is_evolution_id?: number | null;
  /**
   * First Element Id
   */
  first_element_id?: number | null;
  /**
   * Second Element Id
   */
  second_element_id?: number | null;
  /**
   * Type Id
   */
  type_id?: number | null;
  /**
   * Character Id
   */
  character_id?: number | null;
  /**
   * First Attack Id
   */
  first_attack_id?: number | null;
  /**
   * Second Attack Id
   */
  second_attack_id?: number | null;
  /**
   * Ability Id
   */
  ability_id?: number | null;
  /**
   * Association Id
   */
  association_id?: number | null;
  /**
   * Health
   */
  health?: number | null;
  /**
   * Physical Defence
   */
  physical_defence?: number | null;
  /**
   * Magic Defence
   */
  magic_defence?: number | null;
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Code
   */
  code: number;
  /**
   * Image
   */
  image?: string | null;
  /**
   * Overlay Image
   */
  overlay_image?: string | null;
  /**
   * Forces
   */
  forces?: {
    [key: string]: unknown;
  } | null;
};

/**
 * CardRead
 */
export type CardRead = {
  /**
   * Is Evolution Id
   */
  is_evolution_id?: number | null;
  /**
   * First Element Id
   */
  first_element_id?: number | null;
  /**
   * Second Element Id
   */
  second_element_id?: number | null;
  /**
   * Type Id
   */
  type_id?: number | null;
  /**
   * Character Id
   */
  character_id?: number | null;
  /**
   * First Attack Id
   */
  first_attack_id?: number | null;
  /**
   * Second Attack Id
   */
  second_attack_id?: number | null;
  /**
   * Ability Id
   */
  ability_id?: number | null;
  /**
   * Association Id
   */
  association_id?: number | null;
  /**
   * Health
   */
  health?: number | null;
  /**
   * Physical Defence
   */
  physical_defence?: number | null;
  /**
   * Magic Defence
   */
  magic_defence?: number | null;
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Code
   */
  code: number;
  /**
   * Image
   */
  image?: string | null;
  /**
   * Overlay Image
   */
  overlay_image?: string | null;
  /**
   * Forces
   */
  forces?: Array<{
    [key: string]: unknown;
  }> | null;
  /**
   * Id
   */
  id: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Handle
   */
  handle: string;
};

/**
 * CardReadWithRelations
 */
export type CardReadWithRelations = {
  /**
   * Is Evolution Id
   */
  is_evolution_id?: number | null;
  /**
   * First Element Id
   */
  first_element_id?: number | null;
  /**
   * Second Element Id
   */
  second_element_id?: number | null;
  /**
   * Type Id
   */
  type_id?: number | null;
  /**
   * Character Id
   */
  character_id?: number | null;
  /**
   * First Attack Id
   */
  first_attack_id?: number | null;
  /**
   * Second Attack Id
   */
  second_attack_id?: number | null;
  /**
   * Ability Id
   */
  ability_id?: number | null;
  /**
   * Association Id
   */
  association_id?: number | null;
  /**
   * Health
   */
  health?: number | null;
  /**
   * Physical Defence
   */
  physical_defence?: number | null;
  /**
   * Magic Defence
   */
  magic_defence?: number | null;
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Code
   */
  code: number;
  /**
   * Image
   */
  image?: string | null;
  /**
   * Overlay Image
   */
  overlay_image?: string | null;
  /**
   * Forces
   */
  forces?: Array<{
    [key: string]: unknown;
  }> | null;
  /**
   * Id
   */
  id: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Handle
   */
  handle: string;
  first_element?: ElementRead | null;
  second_element?: ElementRead | null;
  type?: TypeRead | null;
  character?: CharacterRead | null;
  first_attack?: AttackReadWithElement | null;
  second_attack?: AttackReadWithElement | null;
  ability?: AbilityRead | null;
  association?: AssociationRead | null;
  is_evolution?: CardRead | null;
  /**
   * Next Evolutions
   */
  next_evolutions?: Array<CardRead> | null;
  /**
   * Strengths
   */
  strengths?: Array<number> | null;
  /**
   * Weaknesses
   */
  weaknesses?: Array<number> | null;
};

/**
 * CharacterCreate
 */
export type CharacterCreate = {
  /**
   * Label
   */
  label: string;
  /**
   * Icon
   */
  icon?: string | null;
};

/**
 * CharacterRead
 */
export type CharacterRead = {
  /**
   * Label
   */
  label: string;
  /**
   * Icon
   */
  icon?: string | null;
  /**
   * Id
   */
  id: number;
};

/**
 * ConnectedData
 *
 * Data for connected message.
 */
export type ConnectedData = {
  /**
   * Player Id
   */
  player_id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Message
   */
  message: string;
};

/**
 * ConnectedMessage
 *
 * Connection established.
 */
export type ConnectedMessage = {
  data: ConnectedData;
};

/**
 * CreateGameData
 *
 * Data for create_game message.
 */
export type CreateGameData = {
  [key: string]: unknown;
};

/**
 * CreateGameMessage
 *
 * Create a new game room.
 */
export type CreateGameMessage = {
  data?: CreateGameData;
};

/**
 * DeckCreate
 *
 * Schema for creating a deck.
 */
export type DeckCreate = {
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
};

/**
 * DeckReadSummary
 *
 * Lightweight schema for deck listing (without full card data).
 */
export type DeckReadSummary = {
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Id
   */
  id: number;
  /**
   * User Id
   */
  user_id: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Updated At
   */
  updated_at: string;
  /**
   * Card Count
   */
  card_count?: number;
  /**
   * Is Valid For Playing
   */
  is_valid_for_playing?: boolean;
};

/**
 * DeckReadWithCards
 *
 * Schema for reading a deck with its cards.
 */
export type DeckReadWithCards = {
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Id
   */
  id: number;
  /**
   * User Id
   */
  user_id: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Updated At
   */
  updated_at: string;
  /**
   * Cards
   */
  cards?: Array<CardReadWithRelations>;
  /**
   * Is Valid For Playing
   */
  is_valid_for_playing?: boolean;
};

/**
 * DeckUpdate
 *
 * Schema for updating a deck.
 */
export type DeckUpdate = {
  /**
   * Name
   */
  name?: string | null;
  /**
   * Description
   */
  description?: string | null;
};

/**
 * ElementCreate
 */
export type ElementCreate = {
  /**
   * Label
   */
  label: string;
  /**
   * Icon
   */
  icon?: string | null;
  /**
   * Color
   */
  color?: string | null;
  /**
   * Strengths
   */
  strengths?: Array<number> | null;
  /**
   * Weaknesses
   */
  weaknesses?: Array<number> | null;
};

/**
 * ElementRead
 */
export type ElementRead = {
  /**
   * Label
   */
  label: string;
  /**
   * Icon
   */
  icon?: string | null;
  /**
   * Color
   */
  color?: string | null;
  /**
   * Strengths
   */
  strengths?: Array<number> | null;
  /**
   * Weaknesses
   */
  weaknesses?: Array<number> | null;
  /**
   * Id
   */
  id: number;
};

/**
 * ErrorData
 *
 * Data for error message.
 */
export type ErrorData = {
  /**
   * Message
   */
  message: string;
};

/**
 * ErrorMessage
 *
 * Error message.
 */
export type ErrorMessage = {
  data: ErrorData;
};

/**
 * GameCreatedData
 *
 * Data for game_created message.
 */
export type GameCreatedData = {
  /**
   * Room
   */
  room: {
    [key: string]: unknown;
  };
};

/**
 * GameCreatedMessage
 *
 * Game room created successfully.
 */
export type GameCreatedMessage = {
  data: GameCreatedData;
};

/**
 * GameJoinedData
 *
 * Data for game_joined message.
 */
export type GameJoinedData = {
  /**
   * Room
   */
  room: {
    [key: string]: unknown;
  };
};

/**
 * GameJoinedMessage
 *
 * Successfully joined a game.
 */
export type GameJoinedMessage = {
  data: GameJoinedData;
};

/**
 * GameLeftData
 *
 * Data for game_left message.
 */
export type GameLeftData = {
  [key: string]: unknown;
};

/**
 * GameLeftMessage
 *
 * Left the game.
 */
export type GameLeftMessage = {
  data?: GameLeftData;
};

/**
 * GameStartedData
 *
 * Data for game_started message.
 */
export type GameStartedData = {
  /**
   * Success
   */
  success: boolean;
  /**
   * Game State
   */
  game_state: {
    [key: string]: unknown;
  };
  /**
   * Events
   */
  events: Array<{
    [key: string]: unknown;
  }>;
  /**
   * Valid Actions
   */
  valid_actions?: Array<{
    [key: string]: unknown;
  }>;
};

/**
 * GameStartedMessage
 *
 * Game has started.
 */
export type GameStartedMessage = {
  data: GameStartedData;
};

/**
 * GameStateData
 *
 * Data for game_state message.
 */
export type GameStateData = {
  /**
   * State
   */
  state?: {
    [key: string]: unknown;
  } | null;
};

/**
 * GameStateMessage
 *
 * Full game state update.
 */
export type GameStateMessage = {
  data?: GameStateData;
};

/**
 * GetStateData
 *
 * Data for get_state message.
 */
export type GetStateData = {
  [key: string]: unknown;
};

/**
 * GetStateMessage
 *
 * Request current game state.
 */
export type GetStateMessage = {
  data?: GetStateData;
};

/**
 * GetValidActionsData
 *
 * Data for get_valid_actions message.
 */
export type GetValidActionsData = {
  [key: string]: unknown;
};

/**
 * GetValidActionsMessage
 *
 * Request valid actions for player.
 */
export type GetValidActionsMessage = {
  data?: GetValidActionsData;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * JoinGameData
 *
 * Data for join_game message.
 */
export type JoinGameData = {
  /**
   * Room Id
   */
  room_id: string;
};

/**
 * JoinGameMessage
 *
 * Join an existing game room.
 */
export type JoinGameMessage = {
  data: JoinGameData;
};

/**
 * LeaveGameData
 *
 * Data for leave_game message.
 */
export type LeaveGameData = {
  [key: string]: unknown;
};

/**
 * LeaveGameMessage
 *
 * Leave the current game.
 */
export type LeaveGameMessage = {
  data?: LeaveGameData;
};

/**
 * ListRoomsData
 *
 * Data for list_rooms message.
 */
export type ListRoomsData = {
  [key: string]: unknown;
};

/**
 * ListRoomsMessage
 *
 * List all available game rooms.
 */
export type ListRoomsMessage = {
  data?: ListRoomsData;
};

/**
 * PingData
 *
 * Data for ping message.
 */
export type PingData = {
  [key: string]: unknown;
};

/**
 * PingMessage
 *
 * Keep-alive ping.
 */
export type PingMessage = {
  data?: PingData;
};

/**
 * PlayerJoinedData
 *
 * Data for player_joined message.
 */
export type PlayerJoinedData = {
  /**
   * Player Id
   */
  player_id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Room
   */
  room: {
    [key: string]: unknown;
  };
};

/**
 * PlayerJoinedMessage
 *
 * Another player joined.
 */
export type PlayerJoinedMessage = {
  data: PlayerJoinedData;
};

/**
 * PlayerLeftData
 *
 * Data for player_left message.
 */
export type PlayerLeftData = {
  /**
   * Player Id
   */
  player_id: string;
  /**
   * Room
   */
  room: {
    [key: string]: unknown;
  };
};

/**
 * PlayerLeftMessage
 *
 * A player left.
 */
export type PlayerLeftMessage = {
  data: PlayerLeftData;
};

/**
 * PongData
 *
 * Data for pong message.
 */
export type PongData = {
  [key: string]: unknown;
};

/**
 * PongMessage
 *
 * Response to ping.
 */
export type PongMessage = {
  data?: PongData;
};

/**
 * RoomsListData
 *
 * Data for rooms_list message.
 */
export type RoomsListData = {
  /**
   * Rooms
   */
  rooms: Array<{
    [key: string]: unknown;
  }>;
};

/**
 * RoomsListMessage
 *
 * List of available rooms.
 */
export type RoomsListMessage = {
  data?: RoomsListData;
};

/**
 * StartGameData
 *
 * Data for start_game message.
 */
export type StartGameData = {
  [key: string]: unknown;
};

/**
 * StartGameMessage
 *
 * Start the game (host only).
 */
export type StartGameMessage = {
  data?: StartGameData;
};

/**
 * Token
 *
 * Schema for access token response.
 */
export type Token = {
  /**
   * Access Token
   */
  access_token: string;
  /**
   * Token Type
   */
  token_type: string;
};

/**
 * TypeCreate
 */
export type TypeCreate = {
  /**
   * Label
   */
  label: string;
  /**
   * Icon
   */
  icon?: string | null;
};

/**
 * TypeRead
 */
export type TypeRead = {
  /**
   * Label
   */
  label: string;
  /**
   * Icon
   */
  icon?: string | null;
  /**
   * Id
   */
  id: number;
};

/**
 * UserCreate
 *
 * Schema for creating a new user.
 */
export type UserCreate = {
  /**
   * Username
   */
  username: string;
  /**
   * Email
   */
  email?: string | null;
  /**
   * Full Name
   */
  full_name?: string | null;
  /**
   * Password
   */
  password: string;
};

/**
 * UserRead
 *
 * Schema for reading user data (excludes password).
 */
export type UserRead = {
  /**
   * Username
   */
  username: string;
  /**
   * Email
   */
  email?: string | null;
  /**
   * Full Name
   */
  full_name?: string | null;
  /**
   * Disabled
   */
  disabled?: boolean;
  /**
   * Id
   */
  id: number;
  /**
   * Created At
   */
  created_at: string;
};

/**
 * ValidActionsData
 *
 * Data for valid_actions message.
 */
export type ValidActionsData = {
  /**
   * Actions
   */
  actions: Array<{
    [key: string]: unknown;
  }>;
};

/**
 * ValidActionsMessage
 *
 * List of valid actions.
 */
export type ValidActionsMessage = {
  data?: ValidActionsData;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

export type LoginForAccessTokenAuthTokenPostData = {
  body: BodyLoginForAccessTokenAuthTokenPost;
  path?: never;
  query?: never;
  url: "/auth/token";
};

export type LoginForAccessTokenAuthTokenPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type LoginForAccessTokenAuthTokenPostError =
  LoginForAccessTokenAuthTokenPostErrors[keyof LoginForAccessTokenAuthTokenPostErrors];

export type LoginForAccessTokenAuthTokenPostResponses = {
  /**
   * Successful Response
   */
  200: Token;
};

export type LoginForAccessTokenAuthTokenPostResponse =
  LoginForAccessTokenAuthTokenPostResponses[keyof LoginForAccessTokenAuthTokenPostResponses];

export type RegisterUserAuthRegisterPostData = {
  body: UserCreate;
  path?: never;
  query?: never;
  url: "/auth/register";
};

export type RegisterUserAuthRegisterPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RegisterUserAuthRegisterPostError =
  RegisterUserAuthRegisterPostErrors[keyof RegisterUserAuthRegisterPostErrors];

export type RegisterUserAuthRegisterPostResponses = {
  /**
   * Successful Response
   */
  201: UserRead;
};

export type RegisterUserAuthRegisterPostResponse =
  RegisterUserAuthRegisterPostResponses[keyof RegisterUserAuthRegisterPostResponses];

export type ReadUsersMeAuthMeGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/auth/me";
};

export type ReadUsersMeAuthMeGetResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type ReadUsersMeAuthMeGetResponse =
  ReadUsersMeAuthMeGetResponses[keyof ReadUsersMeAuthMeGetResponses];

export type GetAllElementsElementsGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/elements";
};

export type GetAllElementsElementsGetResponses = {
  /**
   * Response Get All Elements Elements Get
   *
   * Successful Response
   */
  200: Array<ElementRead>;
};

export type GetAllElementsElementsGetResponse =
  GetAllElementsElementsGetResponses[keyof GetAllElementsElementsGetResponses];

export type CreateElementElementsPostData = {
  body: ElementCreate;
  path?: never;
  query?: never;
  url: "/elements";
};

export type CreateElementElementsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateElementElementsPostError =
  CreateElementElementsPostErrors[keyof CreateElementElementsPostErrors];

export type CreateElementElementsPostResponses = {
  /**
   * Successful Response
   */
  201: ElementRead;
};

export type CreateElementElementsPostResponse =
  CreateElementElementsPostResponses[keyof CreateElementElementsPostResponses];

export type GetElementElementsValueGetData = {
  body?: never;
  path: {
    /**
     * Value
     */
    value: string;
  };
  query?: never;
  url: "/elements/{value}";
};

export type GetElementElementsValueGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetElementElementsValueGetError =
  GetElementElementsValueGetErrors[keyof GetElementElementsValueGetErrors];

export type GetElementElementsValueGetResponses = {
  /**
   * Successful Response
   */
  200: ElementRead;
};

export type GetElementElementsValueGetResponse =
  GetElementElementsValueGetResponses[keyof GetElementElementsValueGetResponses];

export type DeleteElementElementsElementIdDeleteData = {
  body?: never;
  path: {
    /**
     * Element Id
     */
    element_id: number;
  };
  query?: never;
  url: "/elements/{element_id}";
};

export type DeleteElementElementsElementIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteElementElementsElementIdDeleteError =
  DeleteElementElementsElementIdDeleteErrors[keyof DeleteElementElementsElementIdDeleteErrors];

export type DeleteElementElementsElementIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetAllTypesTypesGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/types";
};

export type GetAllTypesTypesGetResponses = {
  /**
   * Response Get All Types Types Get
   *
   * Successful Response
   */
  200: Array<TypeRead>;
};

export type GetAllTypesTypesGetResponse =
  GetAllTypesTypesGetResponses[keyof GetAllTypesTypesGetResponses];

export type CreateTypeTypesPostData = {
  body: TypeCreate;
  path?: never;
  query?: never;
  url: "/types";
};

export type CreateTypeTypesPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateTypeTypesPostError =
  CreateTypeTypesPostErrors[keyof CreateTypeTypesPostErrors];

export type CreateTypeTypesPostResponses = {
  /**
   * Successful Response
   */
  201: TypeRead;
};

export type CreateTypeTypesPostResponse =
  CreateTypeTypesPostResponses[keyof CreateTypeTypesPostResponses];

export type GetTypeTypesValueGetData = {
  body?: never;
  path: {
    /**
     * Value
     */
    value: string;
  };
  query?: never;
  url: "/types/{value}";
};

export type GetTypeTypesValueGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetTypeTypesValueGetError =
  GetTypeTypesValueGetErrors[keyof GetTypeTypesValueGetErrors];

export type GetTypeTypesValueGetResponses = {
  /**
   * Successful Response
   */
  200: TypeRead;
};

export type GetTypeTypesValueGetResponse =
  GetTypeTypesValueGetResponses[keyof GetTypeTypesValueGetResponses];

export type DeleteTypeTypesTypeIdDeleteData = {
  body?: never;
  path: {
    /**
     * Type Id
     */
    type_id: number;
  };
  query?: never;
  url: "/types/{type_id}";
};

export type DeleteTypeTypesTypeIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteTypeTypesTypeIdDeleteError =
  DeleteTypeTypesTypeIdDeleteErrors[keyof DeleteTypeTypesTypeIdDeleteErrors];

export type DeleteTypeTypesTypeIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetAllCharactersCharactersGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/characters";
};

export type GetAllCharactersCharactersGetResponses = {
  /**
   * Response Get All Characters Characters Get
   *
   * Successful Response
   */
  200: Array<CharacterRead>;
};

export type GetAllCharactersCharactersGetResponse =
  GetAllCharactersCharactersGetResponses[keyof GetAllCharactersCharactersGetResponses];

export type CreateCharacterCharactersPostData = {
  body: CharacterCreate;
  path?: never;
  query?: never;
  url: "/characters";
};

export type CreateCharacterCharactersPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateCharacterCharactersPostError =
  CreateCharacterCharactersPostErrors[keyof CreateCharacterCharactersPostErrors];

export type CreateCharacterCharactersPostResponses = {
  /**
   * Successful Response
   */
  201: CharacterRead;
};

export type CreateCharacterCharactersPostResponse =
  CreateCharacterCharactersPostResponses[keyof CreateCharacterCharactersPostResponses];

export type GetCharacterCharactersValueGetData = {
  body?: never;
  path: {
    /**
     * Value
     */
    value: string;
  };
  query?: never;
  url: "/characters/{value}";
};

export type GetCharacterCharactersValueGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetCharacterCharactersValueGetError =
  GetCharacterCharactersValueGetErrors[keyof GetCharacterCharactersValueGetErrors];

export type GetCharacterCharactersValueGetResponses = {
  /**
   * Successful Response
   */
  200: CharacterRead;
};

export type GetCharacterCharactersValueGetResponse =
  GetCharacterCharactersValueGetResponses[keyof GetCharacterCharactersValueGetResponses];

export type DeleteCharacterCharactersCharacterIdDeleteData = {
  body?: never;
  path: {
    /**
     * Character Id
     */
    character_id: number;
  };
  query?: never;
  url: "/characters/{character_id}";
};

export type DeleteCharacterCharactersCharacterIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteCharacterCharactersCharacterIdDeleteError =
  DeleteCharacterCharactersCharacterIdDeleteErrors[keyof DeleteCharacterCharactersCharacterIdDeleteErrors];

export type DeleteCharacterCharactersCharacterIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetAllAttacksAttacksGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/attacks";
};

export type GetAllAttacksAttacksGetResponses = {
  /**
   * Response Get All Attacks Attacks Get
   *
   * Successful Response
   */
  200: Array<AttackReadWithElement>;
};

export type GetAllAttacksAttacksGetResponse =
  GetAllAttacksAttacksGetResponses[keyof GetAllAttacksAttacksGetResponses];

export type CreateAttackAttacksPostData = {
  body: AttackCreate;
  path?: never;
  query?: never;
  url: "/attacks";
};

export type CreateAttackAttacksPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateAttackAttacksPostError =
  CreateAttackAttacksPostErrors[keyof CreateAttackAttacksPostErrors];

export type CreateAttackAttacksPostResponses = {
  /**
   * Successful Response
   */
  201: AttackReadWithElement;
};

export type CreateAttackAttacksPostResponse =
  CreateAttackAttacksPostResponses[keyof CreateAttackAttacksPostResponses];

export type GetAttackAttacksValueGetData = {
  body?: never;
  path: {
    /**
     * Value
     */
    value: string;
  };
  query?: never;
  url: "/attacks/{value}";
};

export type GetAttackAttacksValueGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetAttackAttacksValueGetError =
  GetAttackAttacksValueGetErrors[keyof GetAttackAttacksValueGetErrors];

export type GetAttackAttacksValueGetResponses = {
  /**
   * Successful Response
   */
  200: AttackReadWithElement;
};

export type GetAttackAttacksValueGetResponse =
  GetAttackAttacksValueGetResponses[keyof GetAttackAttacksValueGetResponses];

export type DeleteAttackAttacksAttackIdDeleteData = {
  body?: never;
  path: {
    /**
     * Attack Id
     */
    attack_id: number;
  };
  query?: never;
  url: "/attacks/{attack_id}";
};

export type DeleteAttackAttacksAttackIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteAttackAttacksAttackIdDeleteError =
  DeleteAttackAttacksAttackIdDeleteErrors[keyof DeleteAttackAttacksAttackIdDeleteErrors];

export type DeleteAttackAttacksAttackIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetAllAbilitiesAbilitiesGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/abilities";
};

export type GetAllAbilitiesAbilitiesGetResponses = {
  /**
   * Response Get All Abilities Abilities Get
   *
   * Successful Response
   */
  200: Array<AbilityRead>;
};

export type GetAllAbilitiesAbilitiesGetResponse =
  GetAllAbilitiesAbilitiesGetResponses[keyof GetAllAbilitiesAbilitiesGetResponses];

export type CreateAbilityAbilitiesPostData = {
  body: AbilityCreate;
  path?: never;
  query?: never;
  url: "/abilities";
};

export type CreateAbilityAbilitiesPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateAbilityAbilitiesPostError =
  CreateAbilityAbilitiesPostErrors[keyof CreateAbilityAbilitiesPostErrors];

export type CreateAbilityAbilitiesPostResponses = {
  /**
   * Successful Response
   */
  201: AbilityRead;
};

export type CreateAbilityAbilitiesPostResponse =
  CreateAbilityAbilitiesPostResponses[keyof CreateAbilityAbilitiesPostResponses];

export type GetAbilityAbilitiesValueGetData = {
  body?: never;
  path: {
    /**
     * Value
     */
    value: string;
  };
  query?: never;
  url: "/abilities/{value}";
};

export type GetAbilityAbilitiesValueGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetAbilityAbilitiesValueGetError =
  GetAbilityAbilitiesValueGetErrors[keyof GetAbilityAbilitiesValueGetErrors];

export type GetAbilityAbilitiesValueGetResponses = {
  /**
   * Successful Response
   */
  200: AbilityRead;
};

export type GetAbilityAbilitiesValueGetResponse =
  GetAbilityAbilitiesValueGetResponses[keyof GetAbilityAbilitiesValueGetResponses];

export type DeleteAbilityAbilitiesAbilityIdDeleteData = {
  body?: never;
  path: {
    /**
     * Ability Id
     */
    ability_id: number;
  };
  query?: never;
  url: "/abilities/{ability_id}";
};

export type DeleteAbilityAbilitiesAbilityIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteAbilityAbilitiesAbilityIdDeleteError =
  DeleteAbilityAbilitiesAbilityIdDeleteErrors[keyof DeleteAbilityAbilitiesAbilityIdDeleteErrors];

export type DeleteAbilityAbilitiesAbilityIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetAllAssociationsAssociationsGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/associations";
};

export type GetAllAssociationsAssociationsGetResponses = {
  /**
   * Response Get All Associations Associations Get
   *
   * Successful Response
   */
  200: Array<AssociationRead>;
};

export type GetAllAssociationsAssociationsGetResponse =
  GetAllAssociationsAssociationsGetResponses[keyof GetAllAssociationsAssociationsGetResponses];

export type CreateAssociationAssociationsPostData = {
  body: AssociationCreate;
  path?: never;
  query?: never;
  url: "/associations";
};

export type CreateAssociationAssociationsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateAssociationAssociationsPostError =
  CreateAssociationAssociationsPostErrors[keyof CreateAssociationAssociationsPostErrors];

export type CreateAssociationAssociationsPostResponses = {
  /**
   * Successful Response
   */
  201: AssociationRead;
};

export type CreateAssociationAssociationsPostResponse =
  CreateAssociationAssociationsPostResponses[keyof CreateAssociationAssociationsPostResponses];

export type GetAssociationAssociationsValueGetData = {
  body?: never;
  path: {
    /**
     * Value
     */
    value: string;
  };
  query?: never;
  url: "/associations/{value}";
};

export type GetAssociationAssociationsValueGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetAssociationAssociationsValueGetError =
  GetAssociationAssociationsValueGetErrors[keyof GetAssociationAssociationsValueGetErrors];

export type GetAssociationAssociationsValueGetResponses = {
  /**
   * Successful Response
   */
  200: AssociationRead;
};

export type GetAssociationAssociationsValueGetResponse =
  GetAssociationAssociationsValueGetResponses[keyof GetAssociationAssociationsValueGetResponses];

export type DeleteAssociationAssociationsAssociationIdDeleteData = {
  body?: never;
  path: {
    /**
     * Association Id
     */
    association_id: number;
  };
  query?: never;
  url: "/associations/{association_id}";
};

export type DeleteAssociationAssociationsAssociationIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteAssociationAssociationsAssociationIdDeleteError =
  DeleteAssociationAssociationsAssociationIdDeleteErrors[keyof DeleteAssociationAssociationsAssociationIdDeleteErrors];

export type DeleteAssociationAssociationsAssociationIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetAllCardsCardsGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/cards";
};

export type GetAllCardsCardsGetResponses = {
  /**
   * Response Get All Cards Cards Get
   *
   * Successful Response
   */
  200: Array<CardReadWithRelations>;
};

export type GetAllCardsCardsGetResponse =
  GetAllCardsCardsGetResponses[keyof GetAllCardsCardsGetResponses];

export type CreateCardCardsPostData = {
  body: CardCreate;
  path?: never;
  query?: never;
  url: "/cards";
};

export type CreateCardCardsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateCardCardsPostError =
  CreateCardCardsPostErrors[keyof CreateCardCardsPostErrors];

export type CreateCardCardsPostResponses = {
  /**
   * Successful Response
   */
  201: CardReadWithRelations;
};

export type CreateCardCardsPostResponse =
  CreateCardCardsPostResponses[keyof CreateCardCardsPostResponses];

export type GetCardCardsValueGetData = {
  body?: never;
  path: {
    /**
     * Value
     */
    value: string;
  };
  query?: never;
  url: "/cards/{value}";
};

export type GetCardCardsValueGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetCardCardsValueGetError =
  GetCardCardsValueGetErrors[keyof GetCardCardsValueGetErrors];

export type GetCardCardsValueGetResponses = {
  /**
   * Response Get Card Cards  Value  Get
   *
   * Successful Response
   */
  200: Array<CardReadWithRelations>;
};

export type GetCardCardsValueGetResponse =
  GetCardCardsValueGetResponses[keyof GetCardCardsValueGetResponses];

export type GetCardsByAttackCardsByAttackAttackCodeGetData = {
  body?: never;
  path: {
    /**
     * Attack Code
     */
    attack_code: number;
  };
  query?: never;
  url: "/cards/by-attack/{attack_code}";
};

export type GetCardsByAttackCardsByAttackAttackCodeGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetCardsByAttackCardsByAttackAttackCodeGetError =
  GetCardsByAttackCardsByAttackAttackCodeGetErrors[keyof GetCardsByAttackCardsByAttackAttackCodeGetErrors];

export type GetCardsByAttackCardsByAttackAttackCodeGetResponses = {
  /**
   * Response Get Cards By Attack Cards By Attack  Attack Code  Get
   *
   * Successful Response
   */
  200: Array<CardReadWithRelations>;
};

export type GetCardsByAttackCardsByAttackAttackCodeGetResponse =
  GetCardsByAttackCardsByAttackAttackCodeGetResponses[keyof GetCardsByAttackCardsByAttackAttackCodeGetResponses];

export type GetCardsByAbilityCardsByAbilityAbilityCodeGetData = {
  body?: never;
  path: {
    /**
     * Ability Code
     */
    ability_code: number;
  };
  query?: never;
  url: "/cards/by-ability/{ability_code}";
};

export type GetCardsByAbilityCardsByAbilityAbilityCodeGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetCardsByAbilityCardsByAbilityAbilityCodeGetError =
  GetCardsByAbilityCardsByAbilityAbilityCodeGetErrors[keyof GetCardsByAbilityCardsByAbilityAbilityCodeGetErrors];

export type GetCardsByAbilityCardsByAbilityAbilityCodeGetResponses = {
  /**
   * Response Get Cards By Ability Cards By Ability  Ability Code  Get
   *
   * Successful Response
   */
  200: Array<CardReadWithRelations>;
};

export type GetCardsByAbilityCardsByAbilityAbilityCodeGetResponse =
  GetCardsByAbilityCardsByAbilityAbilityCodeGetResponses[keyof GetCardsByAbilityCardsByAbilityAbilityCodeGetResponses];

export type GetCardsByAssociationCardsByAssociationAssociationCodeGetData = {
  body?: never;
  path: {
    /**
     * Association Code
     */
    association_code: number;
  };
  query?: never;
  url: "/cards/by-association/{association_code}";
};

export type GetCardsByAssociationCardsByAssociationAssociationCodeGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetCardsByAssociationCardsByAssociationAssociationCodeGetError =
  GetCardsByAssociationCardsByAssociationAssociationCodeGetErrors[keyof GetCardsByAssociationCardsByAssociationAssociationCodeGetErrors];

export type GetCardsByAssociationCardsByAssociationAssociationCodeGetResponses =
  {
    /**
     * Response Get Cards By Association Cards By Association  Association Code  Get
     *
     * Successful Response
     */
    200: Array<CardReadWithRelations>;
  };

export type GetCardsByAssociationCardsByAssociationAssociationCodeGetResponse =
  GetCardsByAssociationCardsByAssociationAssociationCodeGetResponses[keyof GetCardsByAssociationCardsByAssociationAssociationCodeGetResponses];

export type DeleteCardCardsCardIdDeleteData = {
  body?: never;
  path: {
    /**
     * Card Id
     */
    card_id: number;
  };
  query?: never;
  url: "/cards/{card_id}";
};

export type DeleteCardCardsCardIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteCardCardsCardIdDeleteError =
  DeleteCardCardsCardIdDeleteErrors[keyof DeleteCardCardsCardIdDeleteErrors];

export type DeleteCardCardsCardIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetAllDecksDecksGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/decks";
};

export type GetAllDecksDecksGetResponses = {
  /**
   * Response Get All Decks Decks Get
   *
   * Successful Response
   */
  200: Array<DeckReadWithCards>;
};

export type GetAllDecksDecksGetResponse =
  GetAllDecksDecksGetResponses[keyof GetAllDecksDecksGetResponses];

export type CreateDeckDecksPostData = {
  body: DeckCreate;
  path?: never;
  query?: never;
  url: "/decks";
};

export type CreateDeckDecksPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateDeckDecksPostError =
  CreateDeckDecksPostErrors[keyof CreateDeckDecksPostErrors];

export type CreateDeckDecksPostResponses = {
  /**
   * Successful Response
   */
  201: DeckReadWithCards;
};

export type CreateDeckDecksPostResponse =
  CreateDeckDecksPostResponses[keyof CreateDeckDecksPostResponses];

export type GetDeckSummariesDecksSummariesGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/decks/summaries";
};

export type GetDeckSummariesDecksSummariesGetResponses = {
  /**
   * Response Get Deck Summaries Decks Summaries Get
   *
   * Successful Response
   */
  200: Array<DeckReadSummary>;
};

export type GetDeckSummariesDecksSummariesGetResponse =
  GetDeckSummariesDecksSummariesGetResponses[keyof GetDeckSummariesDecksSummariesGetResponses];

export type DeleteDeckDecksDeckIdDeleteData = {
  body?: never;
  path: {
    /**
     * Deck Id
     */
    deck_id: number;
  };
  query?: never;
  url: "/decks/{deck_id}";
};

export type DeleteDeckDecksDeckIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteDeckDecksDeckIdDeleteError =
  DeleteDeckDecksDeckIdDeleteErrors[keyof DeleteDeckDecksDeckIdDeleteErrors];

export type DeleteDeckDecksDeckIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteDeckDecksDeckIdDeleteResponse =
  DeleteDeckDecksDeckIdDeleteResponses[keyof DeleteDeckDecksDeckIdDeleteResponses];

export type GetDeckDecksDeckIdGetData = {
  body?: never;
  path: {
    /**
     * Deck Id
     */
    deck_id: number;
  };
  query?: never;
  url: "/decks/{deck_id}";
};

export type GetDeckDecksDeckIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetDeckDecksDeckIdGetError =
  GetDeckDecksDeckIdGetErrors[keyof GetDeckDecksDeckIdGetErrors];

export type GetDeckDecksDeckIdGetResponses = {
  /**
   * Successful Response
   */
  200: DeckReadWithCards;
};

export type GetDeckDecksDeckIdGetResponse =
  GetDeckDecksDeckIdGetResponses[keyof GetDeckDecksDeckIdGetResponses];

export type UpdateDeckDecksDeckIdPutData = {
  body: DeckUpdate;
  path: {
    /**
     * Deck Id
     */
    deck_id: number;
  };
  query?: never;
  url: "/decks/{deck_id}";
};

export type UpdateDeckDecksDeckIdPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateDeckDecksDeckIdPutError =
  UpdateDeckDecksDeckIdPutErrors[keyof UpdateDeckDecksDeckIdPutErrors];

export type UpdateDeckDecksDeckIdPutResponses = {
  /**
   * Successful Response
   */
  200: DeckReadWithCards;
};

export type UpdateDeckDecksDeckIdPutResponse =
  UpdateDeckDecksDeckIdPutResponses[keyof UpdateDeckDecksDeckIdPutResponses];

export type RemoveCardFromDeckDecksDeckIdCardsCardIdDeleteData = {
  body?: never;
  path: {
    /**
     * Deck Id
     */
    deck_id: number;
    /**
     * Card Id
     */
    card_id: number;
  };
  query?: never;
  url: "/decks/{deck_id}/cards/{card_id}";
};

export type RemoveCardFromDeckDecksDeckIdCardsCardIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RemoveCardFromDeckDecksDeckIdCardsCardIdDeleteError =
  RemoveCardFromDeckDecksDeckIdCardsCardIdDeleteErrors[keyof RemoveCardFromDeckDecksDeckIdCardsCardIdDeleteErrors];

export type RemoveCardFromDeckDecksDeckIdCardsCardIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type RemoveCardFromDeckDecksDeckIdCardsCardIdDeleteResponse =
  RemoveCardFromDeckDecksDeckIdCardsCardIdDeleteResponses[keyof RemoveCardFromDeckDecksDeckIdCardsCardIdDeleteResponses];

export type AddCardToDeckDecksDeckIdCardsCardIdPostData = {
  body?: never;
  path: {
    /**
     * Deck Id
     */
    deck_id: number;
    /**
     * Card Id
     */
    card_id: number;
  };
  query?: never;
  url: "/decks/{deck_id}/cards/{card_id}";
};

export type AddCardToDeckDecksDeckIdCardsCardIdPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AddCardToDeckDecksDeckIdCardsCardIdPostError =
  AddCardToDeckDecksDeckIdCardsCardIdPostErrors[keyof AddCardToDeckDecksDeckIdCardsCardIdPostErrors];

export type AddCardToDeckDecksDeckIdCardsCardIdPostResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type AddCardToDeckDecksDeckIdCardsCardIdPostResponse =
  AddCardToDeckDecksDeckIdCardsCardIdPostResponses[keyof AddCardToDeckDecksDeckIdCardsCardIdPostResponses];

export type ListRoomsGameRoomsGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/game/rooms";
};

export type ListRoomsGameRoomsGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type WsCreateGameTypeGameWebsocketMessagesCreateGamePostData = {
  body: CreateGameMessage;
  path?: never;
  query?: never;
  url: "/game/websocket-messages/create-game";
};

export type WsCreateGameTypeGameWebsocketMessagesCreateGamePostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type WsCreateGameTypeGameWebsocketMessagesCreateGamePostError =
  WsCreateGameTypeGameWebsocketMessagesCreateGamePostErrors[keyof WsCreateGameTypeGameWebsocketMessagesCreateGamePostErrors];

export type WsCreateGameTypeGameWebsocketMessagesCreateGamePostResponses = {
  /**
   * Successful Response
   */
  200: CreateGameMessage;
};

export type WsCreateGameTypeGameWebsocketMessagesCreateGamePostResponse =
  WsCreateGameTypeGameWebsocketMessagesCreateGamePostResponses[keyof WsCreateGameTypeGameWebsocketMessagesCreateGamePostResponses];

export type WsJoinGameTypeGameWebsocketMessagesJoinGamePostData = {
  body: JoinGameMessage;
  path?: never;
  query?: never;
  url: "/game/websocket-messages/join-game";
};

export type WsJoinGameTypeGameWebsocketMessagesJoinGamePostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type WsJoinGameTypeGameWebsocketMessagesJoinGamePostError =
  WsJoinGameTypeGameWebsocketMessagesJoinGamePostErrors[keyof WsJoinGameTypeGameWebsocketMessagesJoinGamePostErrors];

export type WsJoinGameTypeGameWebsocketMessagesJoinGamePostResponses = {
  /**
   * Successful Response
   */
  200: JoinGameMessage;
};

export type WsJoinGameTypeGameWebsocketMessagesJoinGamePostResponse =
  WsJoinGameTypeGameWebsocketMessagesJoinGamePostResponses[keyof WsJoinGameTypeGameWebsocketMessagesJoinGamePostResponses];

export type WsListRoomsTypeGameWebsocketMessagesListRoomsPostData = {
  body: ListRoomsMessage;
  path?: never;
  query?: never;
  url: "/game/websocket-messages/list-rooms";
};

export type WsListRoomsTypeGameWebsocketMessagesListRoomsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type WsListRoomsTypeGameWebsocketMessagesListRoomsPostError =
  WsListRoomsTypeGameWebsocketMessagesListRoomsPostErrors[keyof WsListRoomsTypeGameWebsocketMessagesListRoomsPostErrors];

export type WsListRoomsTypeGameWebsocketMessagesListRoomsPostResponses = {
  /**
   * Successful Response
   */
  200: ListRoomsMessage;
};

export type WsListRoomsTypeGameWebsocketMessagesListRoomsPostResponse =
  WsListRoomsTypeGameWebsocketMessagesListRoomsPostResponses[keyof WsListRoomsTypeGameWebsocketMessagesListRoomsPostResponses];

export type WsStartGameTypeGameWebsocketMessagesStartGamePostData = {
  body: StartGameMessage;
  path?: never;
  query?: never;
  url: "/game/websocket-messages/start-game";
};

export type WsStartGameTypeGameWebsocketMessagesStartGamePostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type WsStartGameTypeGameWebsocketMessagesStartGamePostError =
  WsStartGameTypeGameWebsocketMessagesStartGamePostErrors[keyof WsStartGameTypeGameWebsocketMessagesStartGamePostErrors];

export type WsStartGameTypeGameWebsocketMessagesStartGamePostResponses = {
  /**
   * Successful Response
   */
  200: StartGameMessage;
};

export type WsStartGameTypeGameWebsocketMessagesStartGamePostResponse =
  WsStartGameTypeGameWebsocketMessagesStartGamePostResponses[keyof WsStartGameTypeGameWebsocketMessagesStartGamePostResponses];

export type WsActionTypeGameWebsocketMessagesActionPostData = {
  body: ActionMessage;
  path?: never;
  query?: never;
  url: "/game/websocket-messages/action";
};

export type WsActionTypeGameWebsocketMessagesActionPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type WsActionTypeGameWebsocketMessagesActionPostError =
  WsActionTypeGameWebsocketMessagesActionPostErrors[keyof WsActionTypeGameWebsocketMessagesActionPostErrors];

export type WsActionTypeGameWebsocketMessagesActionPostResponses = {
  /**
   * Successful Response
   */
  200: ActionMessage;
};

export type WsActionTypeGameWebsocketMessagesActionPostResponse =
  WsActionTypeGameWebsocketMessagesActionPostResponses[keyof WsActionTypeGameWebsocketMessagesActionPostResponses];

export type WsGetStateTypeGameWebsocketMessagesGetStatePostData = {
  body: GetStateMessage;
  path?: never;
  query?: never;
  url: "/game/websocket-messages/get-state";
};

export type WsGetStateTypeGameWebsocketMessagesGetStatePostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type WsGetStateTypeGameWebsocketMessagesGetStatePostError =
  WsGetStateTypeGameWebsocketMessagesGetStatePostErrors[keyof WsGetStateTypeGameWebsocketMessagesGetStatePostErrors];

export type WsGetStateTypeGameWebsocketMessagesGetStatePostResponses = {
  /**
   * Successful Response
   */
  200: GetStateMessage;
};

export type WsGetStateTypeGameWebsocketMessagesGetStatePostResponse =
  WsGetStateTypeGameWebsocketMessagesGetStatePostResponses[keyof WsGetStateTypeGameWebsocketMessagesGetStatePostResponses];

export type WsGetValidActionsTypeGameWebsocketMessagesGetValidActionsPostData =
  {
    body: GetValidActionsMessage;
    path?: never;
    query?: never;
    url: "/game/websocket-messages/get-valid-actions";
  };

export type WsGetValidActionsTypeGameWebsocketMessagesGetValidActionsPostErrors =
  {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };

export type WsGetValidActionsTypeGameWebsocketMessagesGetValidActionsPostError =
  WsGetValidActionsTypeGameWebsocketMessagesGetValidActionsPostErrors[keyof WsGetValidActionsTypeGameWebsocketMessagesGetValidActionsPostErrors];

export type WsGetValidActionsTypeGameWebsocketMessagesGetValidActionsPostResponses =
  {
    /**
     * Successful Response
     */
    200: GetValidActionsMessage;
  };

export type WsGetValidActionsTypeGameWebsocketMessagesGetValidActionsPostResponse =
  WsGetValidActionsTypeGameWebsocketMessagesGetValidActionsPostResponses[keyof WsGetValidActionsTypeGameWebsocketMessagesGetValidActionsPostResponses];

export type WsLeaveGameTypeGameWebsocketMessagesLeaveGamePostData = {
  body: LeaveGameMessage;
  path?: never;
  query?: never;
  url: "/game/websocket-messages/leave-game";
};

export type WsLeaveGameTypeGameWebsocketMessagesLeaveGamePostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type WsLeaveGameTypeGameWebsocketMessagesLeaveGamePostError =
  WsLeaveGameTypeGameWebsocketMessagesLeaveGamePostErrors[keyof WsLeaveGameTypeGameWebsocketMessagesLeaveGamePostErrors];

export type WsLeaveGameTypeGameWebsocketMessagesLeaveGamePostResponses = {
  /**
   * Successful Response
   */
  200: LeaveGameMessage;
};

export type WsLeaveGameTypeGameWebsocketMessagesLeaveGamePostResponse =
  WsLeaveGameTypeGameWebsocketMessagesLeaveGamePostResponses[keyof WsLeaveGameTypeGameWebsocketMessagesLeaveGamePostResponses];

export type WsPingTypeGameWebsocketMessagesPingPostData = {
  body: PingMessage;
  path?: never;
  query?: never;
  url: "/game/websocket-messages/ping";
};

export type WsPingTypeGameWebsocketMessagesPingPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type WsPingTypeGameWebsocketMessagesPingPostError =
  WsPingTypeGameWebsocketMessagesPingPostErrors[keyof WsPingTypeGameWebsocketMessagesPingPostErrors];

export type WsPingTypeGameWebsocketMessagesPingPostResponses = {
  /**
   * Successful Response
   */
  200: PingMessage;
};

export type WsPingTypeGameWebsocketMessagesPingPostResponse =
  WsPingTypeGameWebsocketMessagesPingPostResponses[keyof WsPingTypeGameWebsocketMessagesPingPostResponses];

export type WsConnectedTypeGameWebsocketMessagesConnectedGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/game/websocket-messages/connected";
};

export type WsConnectedTypeGameWebsocketMessagesConnectedGetResponses = {
  /**
   * Successful Response
   */
  200: ConnectedMessage;
};

export type WsConnectedTypeGameWebsocketMessagesConnectedGetResponse =
  WsConnectedTypeGameWebsocketMessagesConnectedGetResponses[keyof WsConnectedTypeGameWebsocketMessagesConnectedGetResponses];

export type WsGameCreatedTypeGameWebsocketMessagesGameCreatedGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/game/websocket-messages/game-created";
};

export type WsGameCreatedTypeGameWebsocketMessagesGameCreatedGetResponses = {
  /**
   * Successful Response
   */
  200: GameCreatedMessage;
};

export type WsGameCreatedTypeGameWebsocketMessagesGameCreatedGetResponse =
  WsGameCreatedTypeGameWebsocketMessagesGameCreatedGetResponses[keyof WsGameCreatedTypeGameWebsocketMessagesGameCreatedGetResponses];

export type WsGameJoinedTypeGameWebsocketMessagesGameJoinedGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/game/websocket-messages/game-joined";
};

export type WsGameJoinedTypeGameWebsocketMessagesGameJoinedGetResponses = {
  /**
   * Successful Response
   */
  200: GameJoinedMessage;
};

export type WsGameJoinedTypeGameWebsocketMessagesGameJoinedGetResponse =
  WsGameJoinedTypeGameWebsocketMessagesGameJoinedGetResponses[keyof WsGameJoinedTypeGameWebsocketMessagesGameJoinedGetResponses];

export type WsPlayerJoinedTypeGameWebsocketMessagesPlayerJoinedGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/game/websocket-messages/player-joined";
};

export type WsPlayerJoinedTypeGameWebsocketMessagesPlayerJoinedGetResponses = {
  /**
   * Successful Response
   */
  200: PlayerJoinedMessage;
};

export type WsPlayerJoinedTypeGameWebsocketMessagesPlayerJoinedGetResponse =
  WsPlayerJoinedTypeGameWebsocketMessagesPlayerJoinedGetResponses[keyof WsPlayerJoinedTypeGameWebsocketMessagesPlayerJoinedGetResponses];

export type WsPlayerLeftTypeGameWebsocketMessagesPlayerLeftGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/game/websocket-messages/player-left";
};

export type WsPlayerLeftTypeGameWebsocketMessagesPlayerLeftGetResponses = {
  /**
   * Successful Response
   */
  200: PlayerLeftMessage;
};

export type WsPlayerLeftTypeGameWebsocketMessagesPlayerLeftGetResponse =
  WsPlayerLeftTypeGameWebsocketMessagesPlayerLeftGetResponses[keyof WsPlayerLeftTypeGameWebsocketMessagesPlayerLeftGetResponses];

export type WsGameStartedTypeGameWebsocketMessagesGameStartedGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/game/websocket-messages/game-started";
};

export type WsGameStartedTypeGameWebsocketMessagesGameStartedGetResponses = {
  /**
   * Successful Response
   */
  200: GameStartedMessage;
};

export type WsGameStartedTypeGameWebsocketMessagesGameStartedGetResponse =
  WsGameStartedTypeGameWebsocketMessagesGameStartedGetResponses[keyof WsGameStartedTypeGameWebsocketMessagesGameStartedGetResponses];

export type WsGameStateTypeGameWebsocketMessagesGameStateGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/game/websocket-messages/game-state";
};

export type WsGameStateTypeGameWebsocketMessagesGameStateGetResponses = {
  /**
   * Successful Response
   */
  200: GameStateMessage;
};

export type WsGameStateTypeGameWebsocketMessagesGameStateGetResponse =
  WsGameStateTypeGameWebsocketMessagesGameStateGetResponses[keyof WsGameStateTypeGameWebsocketMessagesGameStateGetResponses];

export type WsActionResultTypeGameWebsocketMessagesActionResultGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/game/websocket-messages/action-result";
};

export type WsActionResultTypeGameWebsocketMessagesActionResultGetResponses = {
  /**
   * Successful Response
   */
  200: ActionResultMessage;
};

export type WsActionResultTypeGameWebsocketMessagesActionResultGetResponse =
  WsActionResultTypeGameWebsocketMessagesActionResultGetResponses[keyof WsActionResultTypeGameWebsocketMessagesActionResultGetResponses];

export type WsValidActionsTypeGameWebsocketMessagesValidActionsGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/game/websocket-messages/valid-actions";
};

export type WsValidActionsTypeGameWebsocketMessagesValidActionsGetResponses = {
  /**
   * Successful Response
   */
  200: ValidActionsMessage;
};

export type WsValidActionsTypeGameWebsocketMessagesValidActionsGetResponse =
  WsValidActionsTypeGameWebsocketMessagesValidActionsGetResponses[keyof WsValidActionsTypeGameWebsocketMessagesValidActionsGetResponses];

export type WsRoomsListTypeGameWebsocketMessagesRoomsListGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/game/websocket-messages/rooms-list";
};

export type WsRoomsListTypeGameWebsocketMessagesRoomsListGetResponses = {
  /**
   * Successful Response
   */
  200: RoomsListMessage;
};

export type WsRoomsListTypeGameWebsocketMessagesRoomsListGetResponse =
  WsRoomsListTypeGameWebsocketMessagesRoomsListGetResponses[keyof WsRoomsListTypeGameWebsocketMessagesRoomsListGetResponses];

export type WsGameLeftTypeGameWebsocketMessagesGameLeftGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/game/websocket-messages/game-left";
};

export type WsGameLeftTypeGameWebsocketMessagesGameLeftGetResponses = {
  /**
   * Successful Response
   */
  200: GameLeftMessage;
};

export type WsGameLeftTypeGameWebsocketMessagesGameLeftGetResponse =
  WsGameLeftTypeGameWebsocketMessagesGameLeftGetResponses[keyof WsGameLeftTypeGameWebsocketMessagesGameLeftGetResponses];

export type WsErrorTypeGameWebsocketMessagesErrorGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/game/websocket-messages/error";
};

export type WsErrorTypeGameWebsocketMessagesErrorGetResponses = {
  /**
   * Successful Response
   */
  200: ErrorMessage;
};

export type WsErrorTypeGameWebsocketMessagesErrorGetResponse =
  WsErrorTypeGameWebsocketMessagesErrorGetResponses[keyof WsErrorTypeGameWebsocketMessagesErrorGetResponses];

export type WsPongTypeGameWebsocketMessagesPongGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/game/websocket-messages/pong";
};

export type WsPongTypeGameWebsocketMessagesPongGetResponses = {
  /**
   * Successful Response
   */
  200: PongMessage;
};

export type WsPongTypeGameWebsocketMessagesPongGetResponse =
  WsPongTypeGameWebsocketMessagesPongGetResponses[keyof WsPongTypeGameWebsocketMessagesPongGetResponses];

export type RootGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/";
};

export type RootGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};
